# -*- coding: utf-8 -*-
"""Localized article strings for the per-language token study pages.

Placeholders: {L} language name, {o} tokens, {en} English tokens, {ro} ratio now, {rc} ratio on the
GPT-4-era tokenizer, {rank} / {total} rank from cheapest, {cost} / {encost} USD for 1M prompts at $2/1M input.
"""

T = {
"zh-CN": dict(slug="zhongwen-token-gpt", L="简体中文", dec=".",
  title="简体中文在 GPT 中的 Token 数几乎与英文相同（1.03×）",
  desc="同一提示词翻译成 27 种语言实测：简体中文仅为英文的 1.03×，旧版 GPT-4 分词器为 1.53×。",
  cta="用你自己的文本测一测：中文提示词与英文相比要多少 Token 和费用。", btn="打开 Token 计算器",
  h1="怎么测的", intro="我们把同一段客服提示词翻译成 27 种语言，用 OpenAI 当前的 o200k_base 分词器（GPT-4o 及之后的模型）统计 Token。英文需要 {en} 个 Token，{L}需要 **{o} 个，是英文的 {ro}×**，在 27 种语言中排第 {rank} 便宜。",
  plabel="简体中文版本：", h2="结果", th=("语言", "Token", "相对英文", "旧 GPT-4 分词器"),
  h3="为什么", why="分词器主要用英文数据训练，常见英文单词往往是 1 个 Token（\" polite\"、\" customer\"）。o200k 词表也收录了大量常用中文词，所以简体中文几乎不吃亏：",
  h4="与旧分词器相比", old="在 GPT-4 时代的 cl100k 分词器上，同一提示词是英文的 **{rc}×**，现在是 **{ro}×**。繁体中文仍为 1.35×，简繁差距明显。",
  h5="换算成费用", cost="按输入每 100 万 Token 2 美元计算，把这段提示词发送 100 万次：英文 ${encost}，{L} ${cost}。几乎没有差别。",
  h6="省 Token 的小建议", tips=["固定的系统提示词可以用英文或中文，差别不大，重点是删掉重复和客套话。", "分类、抽取、工具调用等中间步骤让模型输出 JSON，只把最终回答用中文。", "对固定前缀使用提示词缓存（Prompt Caching），输入单价会大幅下降。"],
  h7="局限", limits=["只测了一段提示词，不同文本比例可能相差 0.1–0.2。", "Claude 和 Gemini 使用不同分词器，这些数字只适用于 OpenAI 模型。", "译文以机器翻译为基础并经过检查。"],
  full="全部 27 种语言的结果（英文）：[27 种语言对比]({enlink})"),
"zh-TW": dict(slug="zhongwen-fanti-token-gpt", L="繁體中文", dec=".",
  title="繁體中文在 GPT 中比英文多用 35% Token（1.35×）",
  desc="同一提示詞翻成 27 種語言實測：繁體中文為英文的 1.35×，簡體中文只有 1.03×。原因與省錢方法。",
  cta="用你自己的文字測一測：中文提示詞比英文多多少 Token 和費用。", btn="開啟 Token 計算器",
  h1="怎麼測的", intro="我們把同一段客服提示詞翻成 27 種語言，用 OpenAI 目前的 o200k_base 分詞器（GPT-4o 以後的模型）計算 Token。英文需要 {en} 個 Token，{L}需要 **{o} 個，是英文的 {ro}×**，在 27 種語言中排第 {rank} 便宜。",
  plabel="繁體中文版本：", h2="結果", th=("語言", "Token", "相對英文", "舊 GPT-4 分詞器"),
  h3="為什麼", why="分詞器主要以英文資料訓練，常見英文單字通常是 1 個 Token（\" polite\"、\" customer\"）。繁體字的常用詞收錄得比簡體少，常被拆成單字：",
  h4="與舊分詞器相比", old="在 GPT-4 時代的 cl100k 分詞器上，同一提示詞是英文的 **{rc}×**，現在降到 **{ro}×**。不過同樣內容的簡體中文只要 1.03×。",
  h5="換算成費用", cost="以輸入每 100 萬 Token 2 美元計，把這段提示詞送出 100 萬次：英文 ${encost}，{L} ${cost}。若回答也用繁體中文，單價通常高 4–5 倍的輸出 Token 也會乘上同樣倍數。",
  h6="省 Token 的方法", tips=["固定的系統提示詞改用英文撰寫，只讓使用者輸入保持中文。", "分類、擷取、工具呼叫等中間步驟輸出英文或 JSON，只有最後回答用繁體中文。", "對固定前綴使用提示詞快取（Prompt Caching），輸入單價會大幅下降。"],
  h7="限制", limits=["只測了一段提示詞，不同文字的倍數可能差 0.1–0.2。", "Claude 與 Gemini 的分詞器不同，這些數字只適用於 OpenAI 模型。", "譯文以機器翻譯為基礎並經過檢查。"],
  full="全部 27 種語言的結果（英文）：[27 種語言比較]({enlink})"),
"es": dict(slug="tokens-espanol-gpt", L="el español", dec=",",
  title="El español gasta 1,18× más tokens que el inglés en GPT",
  desc="Medí el mismo prompt en 27 idiomas: el español usa 1,18× los tokens del inglés. Por qué y cómo ahorrar.",
  cta="Mide tu propio texto: cuántos tokens y cuánto dinero cuesta tu prompt en español frente al inglés.", btn="Abrir el contador de tokens",
  h1="Cómo lo medí", intro="Traduje el mismo prompt de atención al cliente a 27 idiomas y conté los tokens con o200k_base, el tokenizador actual de OpenAI (GPT-4o y posteriores). En inglés son {en} tokens; en español, **{o}: {ro}× el inglés**, puesto {rank} de {total} (1 = el más barato).",
  plabel="La versión en español:", h2="Resultados", th=("Idioma", "Tokens", "Frente al inglés", "Tokenizador GPT-4 antiguo"),
  h3="Por qué", why="El tokenizador aprende sobre todo de texto en inglés: palabras como \" polite\" o \" customer\" son un solo token, mientras que muchas palabras en español se parten en trozos:",
  h4="Frente al tokenizador antiguo", old="Con el tokenizador de la era GPT-4 (cl100k), el mismo prompt costaba **{rc}×**; hoy es **{ro}×**.",
  h5="En dinero", cost="Con un modelo a 2 $ por millón de tokens de entrada, enviar este prompt un millón de veces cuesta {encost} $ en inglés y {cost} $ en español. Si la respuesta también es en español, el mismo multiplicador se aplica a los tokens de salida, que suelen costar 4–5× más.",
  h6="Cómo ahorrar", tips=["Escribe el prompt de sistema y las instrucciones fijas en inglés; deja en español solo lo que escribe el usuario.", "Pide los pasos intermedios (clasificación, extracción, llamadas a herramientas) en inglés o JSON y solo la respuesta final en español.", "Usa prompt caching para la parte fija del prompt."],
  h7="Limitaciones", limits=["Es un solo prompt; con otros textos la proporción puede variar ±0,1–0,2.", "Claude y Gemini usan otros tokenizadores: estas cifras valen solo para modelos de OpenAI.", "La traducción parte de una traducción automática revisada."],
  full="Resultados completos de los 27 idiomas (en inglés): [comparativa de 27 idiomas]({enlink})"),
"pt": dict(slug="tokens-portugues-gpt", L="o português", dec=",",
  title="O português gasta 1,21× mais tokens que o inglês no GPT",
  desc="Medi o mesmo prompt em 27 idiomas: o português usa 1,21× os tokens do inglês. Por quê e como economizar.",
  cta="Meça seu próprio texto: quantos tokens e quanto dinheiro seu prompt em português custa em relação ao inglês.", btn="Abrir o contador de tokens",
  h1="Como medi", intro="Traduzi o mesmo prompt de atendimento ao cliente para 27 idiomas e contei os tokens com o o200k_base, o tokenizador atual da OpenAI (GPT-4o e posteriores). Em inglês são {en} tokens; em português, **{o}: {ro}× o inglês**, posição {rank} de {total} (1 = o mais barato).",
  plabel="A versão em português:", h2="Resultados", th=("Idioma", "Tokens", "Em relação ao inglês", "Tokenizador antigo do GPT-4"),
  h3="Por quê", why="O tokenizador aprende principalmente com texto em inglês: palavras como \" polite\" ou \" customer\" são um único token, enquanto muitas palavras em português são quebradas em pedaços:",
  h4="Comparado ao tokenizador antigo", old="No tokenizador da era GPT-4 (cl100k), o mesmo prompt custava **{rc}×**; hoje custa **{ro}×**.",
  h5="Em dinheiro", cost="Com um modelo a US$ 2 por milhão de tokens de entrada, enviar este prompt um milhão de vezes custa US$ {encost} em inglês e US$ {cost} em português. Se a resposta também vier em português, o mesmo multiplicador vale para os tokens de saída, que costumam custar 4–5× mais.",
  h6="Como economizar", tips=["Escreva o prompt de sistema e as instruções fixas em inglês; deixe em português só o que o usuário digita.", "Peça as etapas intermediárias (classificação, extração, chamadas de ferramentas) em inglês ou JSON e só a resposta final em português.", "Use prompt caching para a parte fixa do prompt."],
  h7="Limitações", limits=["É um único prompt; com outros textos a proporção pode variar ±0,1–0,2.", "Claude e Gemini usam outros tokenizadores: estes números valem só para modelos da OpenAI.", "A tradução parte de uma tradução automática revisada."],
  full="Resultados completos dos 27 idiomas (em inglês): [comparação de 27 idiomas]({enlink})"),
"fr": dict(slug="tokens-francais-gpt", L="le français", dec=",",
  title="Le français consomme 1,29× plus de tokens que l’anglais dans GPT",
  desc="Le même prompt mesuré dans 27 langues : le français utilise 1,29× les tokens de l’anglais. Pourquoi et comment économiser.",
  cta="Mesurez votre propre texte : combien de tokens et d’argent coûte votre prompt en français par rapport à l’anglais.", btn="Ouvrir le compteur de tokens",
  h1="La méthode", intro="J’ai traduit le même prompt de service client dans 27 langues et compté les tokens avec o200k_base, le tokeniseur actuel d’OpenAI (GPT-4o et suivants). L’anglais demande {en} tokens ; le français **{o}, soit {ro}× l’anglais**, rang {rank} sur {total} (1 = le moins cher).",
  plabel="La version française :", h2="Résultats", th=("Langue", "Tokens", "Par rapport à l’anglais", "Ancien tokeniseur GPT-4"),
  h3="Pourquoi", why="Le tokeniseur apprend surtout sur du texte anglais : des mots comme « polite » ou « customer » tiennent en un seul token, alors que beaucoup de mots français sont découpés en morceaux :",
  h4="Par rapport à l’ancien tokeniseur", old="Avec le tokeniseur de l’époque GPT-4 (cl100k), le même prompt coûtait **{rc}×** ; aujourd’hui **{ro}×**.",
  h5="En argent", cost="Avec un modèle à 2 $ le million de tokens d’entrée, envoyer ce prompt un million de fois coûte {encost} $ en anglais et {cost} $ en français. Si la réponse est aussi en français, le même multiplicateur s’applique aux tokens de sortie, généralement 4 à 5× plus chers.",
  h6="Comment économiser", tips=["Rédigez le prompt système et les consignes fixes en anglais ; gardez en français seulement ce que saisit l’utilisateur.", "Demandez les étapes intermédiaires (classification, extraction, appels d’outils) en anglais ou en JSON, et seule la réponse finale en français.", "Utilisez le prompt caching pour la partie fixe du prompt."],
  h7="Limites", limits=["Un seul prompt mesuré ; selon le texte, le ratio peut varier de ±0,1–0,2.", "Claude et Gemini utilisent d’autres tokeniseurs : ces chiffres ne valent que pour les modèles OpenAI.", "La traduction repose sur une traduction automatique relue."],
  full="Résultats complets des 27 langues (en anglais) : [comparaison de 27 langues]({enlink})"),
"de": dict(slug="tokens-deutsch-gpt", L="Deutsch", dec=",",
  title="Deutsch braucht in GPT 1,26× so viele Tokens wie Englisch",
  desc="Derselbe Prompt in 27 Sprachen gemessen: Deutsch braucht 1,26× die Tokens von Englisch. Warum und wie man spart.",
  cta="Miss deinen eigenen Text: wie viele Tokens und wie viel Geld dein deutscher Prompt im Vergleich zu Englisch kostet.", btn="Token-Zähler öffnen",
  h1="So habe ich gemessen", intro="Ich habe denselben Kundenservice-Prompt in 27 Sprachen übersetzt und die Tokens mit o200k_base gezählt, dem aktuellen Tokenizer von OpenAI (GPT-4o und neuer). Englisch braucht {en} Tokens, Deutsch **{o} – also {ro}× so viele**, Platz {rank} von {total} (1 = am günstigsten).",
  plabel="Die deutsche Fassung:", h2="Ergebnisse", th=("Sprache", "Tokens", "Im Vergleich zu Englisch", "Alter GPT-4-Tokenizer"),
  h3="Warum", why="Der Tokenizer lernt vor allem aus englischem Text: Wörter wie „ polite“ oder „ customer“ sind ein einziger Token, deutsche Wörter – besonders Komposita – werden dagegen zerlegt:",
  h4="Im Vergleich zum alten Tokenizer", old="Mit dem Tokenizer aus der GPT-4-Zeit (cl100k) brauchte derselbe Prompt **{rc}×**, heute **{ro}×**.",
  h5="In Geld", cost="Bei einem Modell mit 2 $ pro 1 Mio. Input-Tokens kostet es {encost} $ auf Englisch und {cost} $ auf Deutsch, diesen Prompt eine Million Mal zu senden. Antwortet das Modell auch auf Deutsch, gilt derselbe Faktor für die Output-Tokens, die meist 4–5× teurer sind.",
  h6="So sparst du", tips=["System-Prompt und feste Anweisungen auf Englisch schreiben; nur die Eingaben der Nutzer bleiben auf Deutsch.", "Zwischenschritte (Klassifizierung, Extraktion, Tool-Aufrufe) auf Englisch oder als JSON ausgeben lassen, nur die finale Antwort auf Deutsch.", "Prompt Caching für den festen Teil des Prompts nutzen."],
  h7="Einschränkungen", limits=["Gemessen wurde ein einziger Prompt; bei anderen Texten kann der Faktor um ±0,1–0,2 abweichen.", "Claude und Gemini haben andere Tokenizer – die Zahlen gelten nur für OpenAI-Modelle.", "Die Übersetzung basiert auf einer geprüften maschinellen Übersetzung."],
  full="Alle Ergebnisse für 27 Sprachen (auf Englisch): [Vergleich von 27 Sprachen]({enlink})"),
"it": dict(slug="token-italiano-gpt", L="l’italiano", dec=",",
  title="L’italiano usa 1,38× i token dell’inglese in GPT",
  desc="Lo stesso prompt misurato in 27 lingue: l’italiano usa 1,38× i token dell’inglese. Perché e come risparmiare.",
  cta="Misura il tuo testo: quanti token e quanti soldi costa il tuo prompt in italiano rispetto all’inglese.", btn="Apri il contatore di token",
  h1="Come ho misurato", intro="Ho tradotto lo stesso prompt di assistenza clienti in 27 lingue e contato i token con o200k_base, il tokenizer attuale di OpenAI (GPT-4o e successivi). In inglese servono {en} token; in italiano **{o}, cioè {ro}× l’inglese**, posizione {rank} su {total} (1 = il più economico).",
  plabel="La versione italiana:", h2="Risultati", th=("Lingua", "Token", "Rispetto all’inglese", "Vecchio tokenizer GPT-4"),
  h3="Perché", why="Il tokenizer impara soprattutto da testo inglese: parole come \" polite\" o \" customer\" sono un solo token, mentre molte parole italiane vengono spezzate:",
  h4="Rispetto al vecchio tokenizer", old="Con il tokenizer dell’epoca GPT-4 (cl100k) lo stesso prompt costava **{rc}×**; oggi **{ro}×**.",
  h5="In denaro", cost="Con un modello a 2 $ per milione di token in input, inviare questo prompt un milione di volte costa {encost} $ in inglese e {cost} $ in italiano. Se anche la risposta è in italiano, lo stesso moltiplicatore vale per i token in output, che di solito costano 4–5× di più.",
  h6="Come risparmiare", tips=["Scrivi il prompt di sistema e le istruzioni fisse in inglese; lascia in italiano solo l’input dell’utente.", "Chiedi i passaggi intermedi (classificazione, estrazione, chiamate a strumenti) in inglese o JSON e solo la risposta finale in italiano.", "Usa il prompt caching per la parte fissa del prompt."],
  h7="Limiti", limits=["È un solo prompt: con altri testi il rapporto può variare di ±0,1–0,2.", "Claude e Gemini usano altri tokenizer: questi numeri valgono solo per i modelli OpenAI.", "La traduzione parte da una traduzione automatica revisionata."],
  full="Risultati completi delle 27 lingue (in inglese): [confronto tra 27 lingue]({enlink})"),
"ru": dict(slug="tokeny-russkiy-gpt", L="русский", dec=",",
  title="Русский в GPT требует в 1,32 раза больше токенов, чем английский",
  desc="Один и тот же промпт на 27 языках: русский — 1,32× токенов английского (раньше 2,15×). Почему и как сэкономить.",
  cta="Измерьте свой текст: сколько токенов и денег стоит ваш промпт на русском по сравнению с английским.", btn="Открыть счётчик токенов",
  h1="Как я измерял", intro="Я перевёл один и тот же промпт службы поддержки на 27 языков и посчитал токены токенизатором o200k_base — его используют современные модели OpenAI (GPT-4o и новее). На английском выходит {en} токена, на русском **{o} — в {ro} раза больше**, {rank}-е место из {total} (1 — самый дешёвый).",
  plabel="Русская версия:", h2="Результаты", th=("Язык", "Токены", "Относительно английского", "Старый токенизатор GPT-4"),
  h3="Почему", why="Токенизатор обучен в основном на английском тексте: слова вроде \" polite\" или \" customer\" — один токен, а русские слова с окончаниями режутся на части:",
  h4="По сравнению со старым токенизатором", old="На токенизаторе времён GPT-4 (cl100k) тот же промпт стоил **{rc}×**, сейчас — **{ro}×**. Кириллица заметно подешевела.",
  h5="В деньгах", cost="При цене 2 $ за 1 млн входных токенов отправка этого промпта миллион раз стоит {encost} $ на английском и {cost} $ на русском. Если ответ тоже на русском, тот же множитель действует и на выходные токены, которые обычно в 4–5 раз дороже.",
  h6="Как сэкономить", tips=["Пишите системный промпт и постоянные инструкции на английском, а на русском оставляйте только ввод пользователя.", "Промежуточные шаги (классификация, извлечение, вызовы инструментов) просите на английском или в JSON, а на русском — только итоговый ответ.", "Используйте кэширование промпта для постоянной части."],
  h7="Ограничения", limits=["Измерен один промпт; для других текстов коэффициент может отличаться на ±0,1–0,2.", "У Claude и Gemini другие токенизаторы — цифры верны только для моделей OpenAI.", "Перевод основан на проверенном машинном переводе."],
  full="Полные результаты по 27 языкам (на английском): [сравнение 27 языков]({enlink})"),
"uk": dict(slug="tokeny-ukrainska-gpt", L="українська", dec=",",
  title="Українська в GPT потребує в 1,88 раза більше токенів, ніж англійська",
  desc="Один промпт 27 мовами: українська — 1,88× токенів англійської (раніше 3,15×). Чому так і як заощадити.",
  cta="Виміряйте свій текст: скільки токенів і грошей коштує ваш промпт українською порівняно з англійською.", btn="Відкрити лічильник токенів",
  h1="Як я вимірював", intro="Я переклав той самий промпт служби підтримки 27 мовами й порахував токени токенізатором o200k_base, який використовують сучасні моделі OpenAI (GPT-4o і новіші). Англійською виходить {en} токени, українською **{o} — у {ro} раза більше**, {rank}-те місце з {total} (1 — найдешевша).",
  plabel="Українська версія:", h2="Результати", th=("Мова", "Токени", "Порівняно з англійською", "Старий токенізатор GPT-4"),
  h3="Чому", why="Токенізатор навчений переважно на англійському тексті: слова на кшталт \" polite\" чи \" customer\" — один токен, а українські слова з закінченнями розбиваються на шматки:",
  h4="Порівняно зі старим токенізатором", old="На токенізаторі часів GPT-4 (cl100k) той самий промпт коштував **{rc}×**, тепер — **{ro}×**. Попри це українська досі серед найдорожчих мов, дорожче лише чеська.",
  h5="У грошах", cost="За ціни 2 $ за 1 млн вхідних токенів надсилання цього промпту мільйон разів коштує {encost} $ англійською і {cost} $ українською. Якщо відповідь теж українською, той самий множник діє й на вихідні токени, які зазвичай у 4–5 разів дорожчі.",
  h6="Як заощадити", tips=["Пишіть системний промпт і сталі інструкції англійською, а українською залишайте лише введення користувача.", "Проміжні кроки (класифікація, вилучення, виклики інструментів) просіть англійською або в JSON, а українською — лише фінальну відповідь.", "Використовуйте кешування промпту для сталої частини."],
  h7="Обмеження", limits=["Виміряно один промпт; для інших текстів коефіцієнт може відрізнятися на ±0,1–0,2.", "У Claude і Gemini інші токенізатори — цифри правильні лише для моделей OpenAI.", "Переклад базується на перевіреному машинному перекладі."],
  full="Повні результати для 27 мов (англійською): [порівняння 27 мов]({enlink})"),
"tr": dict(slug="token-turkce-gpt", L="Türkçe", dec=",",
  title="Türkçe, GPT'de İngilizceden 1,47× daha fazla token harcıyor",
  desc="Aynı istemi 27 dilde ölçtüm: Türkçe, İngilizcenin 1,47× tokenini kullanıyor. Nedeni ve tasarruf yolları.",
  cta="Kendi metninizi ölçün: Türkçe isteminiz İngilizceye göre kaç token ve ne kadar para tutuyor.", btn="Token sayacını aç",
  h1="Nasıl ölçtüm", intro="Aynı müşteri hizmetleri istemini 27 dile çevirdim ve tokenleri OpenAI'nin güncel tokenizer'ı o200k_base ile saydım (GPT-4o ve sonrası). İngilizce {en} token, Türkçe **{o} token: İngilizcenin {ro}× katı**; {total} dil içinde en ucuzdan {rank}. sırada.",
  plabel="Türkçe sürümü:", h2="Sonuçlar", th=("Dil", "Token", "İngilizceye göre", "Eski GPT-4 tokenizer"),
  h3="Neden", why="Tokenizer çoğunlukla İngilizce metinle eğitilir: \" polite\" veya \" customer\" gibi kelimeler tek token iken eklerle uzayan Türkçe kelimeler parçalara bölünür:",
  h4="Eski tokenizer'a göre", old="GPT-4 dönemi tokenizer'ında (cl100k) aynı istem **{rc}×** tutuyordu; bugün **{ro}×**.",
  h5="Parayla", cost="Girdi için 1 milyon token başına 2 $ ücret alan bir modelde bu istemi 1 milyon kez göndermek İngilizcede {encost} $, Türkçede {cost} $ tutar. Yanıt da Türkçe olursa aynı çarpan, genellikle 4–5× daha pahalı olan çıktı tokenlerine de uygulanır.",
  h6="Nasıl tasarruf edilir", tips=["Sistem istemini ve sabit talimatları İngilizce yazın; yalnızca kullanıcı girdisi Türkçe kalsın.", "Ara adımları (sınıflandırma, çıkarma, araç çağrıları) İngilizce ya da JSON olarak alın, yalnızca son yanıt Türkçe olsun.", "İstemin sabit kısmı için prompt caching kullanın."],
  h7="Sınırlamalar", limits=["Tek bir istem ölçüldü; başka metinlerde oran ±0,1–0,2 değişebilir.", "Claude ve Gemini farklı tokenizer kullanır; bu sayılar yalnızca OpenAI modelleri için geçerlidir.", "Çeviri, kontrol edilmiş makine çevirisine dayanır."],
  full="27 dilin tüm sonuçları (İngilizce): [27 dil karşılaştırması]({enlink})"),
"ar": dict(slug="tokens-arabic-gpt", L="العربية", dec=".",
  title="العربية في GPT تستهلك 1.26× رموز الإنجليزية",
  desc="قِسنا الموجّه نفسه بـ27 لغة: العربية 1.26× رموز الإنجليزية بعد أن كانت 3.03×. السبب وطرق التوفير.",
  cta="قِس نصك بنفسك: كم رمزًا وكم دولارًا يكلف موجّهك بالعربية مقارنة بالإنجليزية.", btn="افتح عدّاد الرموز",
  h1="طريقة القياس", intro="ترجمنا موجّه خدمة عملاء واحدًا إلى 27 لغة وعددنا الرموز (Tokens) بمُجزِّئ o200k_base الحالي من OpenAI (‏GPT-4o وما بعده). تحتاج الإنجليزية إلى {en} رمزًا، وتحتاج العربية إلى **{o} رمزًا، أي {ro}× الإنجليزية**، في المرتبة {rank} من {total} (1 = الأرخص).",
  plabel="النسخة العربية:", h2="النتائج", th=("اللغة", "الرموز", "مقارنة بالإنجليزية", "مُجزِّئ GPT-4 القديم"),
  h3="لماذا", why="يتعلّم المُجزِّئ غالبًا من نصوص إنجليزية، فكلمات مثل \" polite\" و\" customer\" رمز واحد، بينما تُقسَّم كلمات عربية كثيرة إلى أجزاء:",
  h4="مقارنة بالمُجزِّئ القديم", old="في مُجزِّئ حقبة GPT-4 ‏(cl100k) كان الموجّه نفسه **{rc}×**، واليوم **{ro}×** فقط. العربية من أكثر اللغات استفادةً من التغيير.",
  h5="بالمال", cost="مع نموذج سعره 2 دولار لكل مليون رمز إدخال، يكلّف إرسال هذا الموجّه مليون مرة {encost} دولارًا بالإنجليزية و{cost} دولارًا بالعربية. وإذا كان الرد بالعربية أيضًا، يُطبَّق المُضاعِف نفسه على رموز الإخراج الأغلى عادةً بـ4–5 مرات.",
  h6="كيف توفّر", tips=["اكتب موجّه النظام والتعليمات الثابتة بالإنجليزية، واترك إدخال المستخدم وحده بالعربية.", "اطلب الخطوات الوسيطة (التصنيف، الاستخراج، استدعاء الأدوات) بالإنجليزية أو JSON، والرد النهائي وحده بالعربية.", "استخدم التخزين المؤقت للموجّه (Prompt Caching) للجزء الثابت."],
  h7="حدود القياس", limits=["قِسنا موجّهًا واحدًا؛ قد تختلف النسبة ±0.1–0.2 مع نصوص أخرى.", "يستخدم Claude وGemini مُجزِّئات مختلفة، فالأرقام تخص نماذج OpenAI فقط.", "الترجمة مبنية على ترجمة آلية تمت مراجعتها."],
  full="النتائج الكاملة للغات الـ27 (بالإنجليزية): [مقارنة 27 لغة]({enlink})"),
"fa": dict(slug="token-farsi-gpt", L="فارسی", dec=".",
  title="فارسی در GPT حدود 1.24 برابر انگلیسی توکن مصرف می‌کند",
  desc="یک پرامپت در ۲۷ زبان: فارسی 1.24× توکن انگلیسی (قبلاً 2.79×). دلیلش و راه‌های صرفه‌جویی.",
  cta="متن خودتان را بسنجید: پرامپت فارسی شما نسبت به انگلیسی چند توکن و چقدر هزینه دارد.", btn="باز کردن توکن‌شمار",
  h1="روش اندازه‌گیری", intro="یک پرامپت پشتیبانی مشتری را به ۲۷ زبان ترجمه کردیم و توکن‌ها را با o200k_base، توکنایزر فعلی OpenAI (‏GPT-4o و بعد از آن) شمردیم. انگلیسی {en} توکن لازم دارد و فارسی **{o} توکن، یعنی {ro}× انگلیسی**؛ رتبه {rank} از {total} (۱ = ارزان‌ترین).",
  plabel="نسخه فارسی:", h2="نتایج", th=("زبان", "توکن", "نسبت به انگلیسی", "توکنایزر قدیمی GPT-4"),
  h3="چرا", why="توکنایزر بیشتر با متن انگلیسی آموزش دیده است؛ واژه‌هایی مثل \" polite\" و \" customer\" یک توکن‌اند، اما بسیاری از واژه‌های فارسی تکه‌تکه می‌شوند:",
  h4="در مقایسه با توکنایزر قدیمی", old="در توکنایزر دوره GPT-4 ‏(cl100k) همین پرامپت **{rc}×** بود و حالا **{ro}×** است؛ یعنی هزینه فارسی به کمتر از نصف رسیده.",
  h5="به پول", cost="با مدلی که برای هر یک میلیون توکن ورودی ۲ دلار می‌گیرد، یک میلیون بار ارسال این پرامپت به انگلیسی {encost} دلار و به فارسی {cost} دلار هزینه دارد. اگر پاسخ هم فارسی باشد، همین ضریب روی توکن‌های خروجی هم اعمال می‌شود که معمولاً ۴ تا ۵ برابر گران‌ترند.",
  h6="راه‌های صرفه‌جویی", tips=["پرامپت سیستم و دستورهای ثابت را انگلیسی بنویسید و فقط ورودی کاربر را فارسی نگه دارید.", "مراحل میانی (دسته‌بندی، استخراج، فراخوانی ابزار) را انگلیسی یا JSON بخواهید و فقط پاسخ نهایی را فارسی.", "برای بخش ثابت پرامپت از کش پرامپت (Prompt Caching) استفاده کنید."],
  h7="محدودیت‌ها", limits=["فقط یک پرامپت سنجیده شد؛ در متن‌های دیگر نسبت ممکن است ±0.1 تا 0.2 تغییر کند.", "Claude و Gemini توکنایزر دیگری دارند؛ این اعداد فقط برای مدل‌های OpenAI است.", "ترجمه بر پایه ترجمه ماشینی بازبینی‌شده است."],
  full="نتایج کامل ۲۷ زبان (به انگلیسی): [مقایسه ۲۷ زبان]({enlink})"),
"hi": dict(slug="tokens-hindi-gpt", L="हिन्दी", dec=".",
  title="GPT में हिन्दी, अंग्रेज़ी से 1.50× टोकन लेती है",
  desc="एक ही प्रॉम्प्ट 27 भाषाओं में मापा: हिन्दी अब 1.50× है, पुराने GPT-4 टोकनाइज़र पर 4.59× थी। कारण और बचत के तरीके।",
  cta="अपना टेक्स्ट मापें: आपका हिन्दी प्रॉम्प्ट अंग्रेज़ी की तुलना में कितने टोकन और कितना पैसा लेता है।", btn="टोकन काउंटर खोलें",
  h1="कैसे मापा", intro="हमने एक ही कस्टमर-सपोर्ट प्रॉम्प्ट का 27 भाषाओं में अनुवाद किया और OpenAI के मौजूदा o200k_base टोकनाइज़र (GPT-4o और नए मॉडल) से टोकन गिने। अंग्रेज़ी में {en} टोकन लगते हैं, हिन्दी में **{o} टोकन — यानी अंग्रेज़ी का {ro}×**; {total} भाषाओं में सबसे सस्ती से गिनें तो {rank}वाँ स्थान।",
  plabel="हिन्दी संस्करण:", h2="नतीजे", th=("भाषा", "टोकन", "अंग्रेज़ी के मुकाबले", "पुराना GPT-4 टोकनाइज़र"),
  h3="ऐसा क्यों", why="टोकनाइज़र ज़्यादातर अंग्रेज़ी टेक्स्ट से सीखता है: \" polite\" या \" customer\" जैसे शब्द एक टोकन होते हैं, जबकि कई हिन्दी शब्द मात्राओं समेत टुकड़ों में बँट जाते हैं:",
  h4="पुराने टोकनाइज़र से तुलना", old="GPT-4 दौर के टोकनाइज़र (cl100k) पर यही प्रॉम्प्ट **{rc}×** था; अब **{ro}×** है। यानी हिन्दी की लागत लगभग एक-तिहाई रह गई है।",
  h5="पैसों में", cost="$2 प्रति 10 लाख इनपुट टोकन वाले मॉडल पर यह प्रॉम्प्ट 10 लाख बार भेजने में अंग्रेज़ी में ${encost} और हिन्दी में ${cost} लगते हैं। जवाब भी हिन्दी में हो तो यही गुणक आउटपुट टोकन पर भी लगता है, जो आम तौर पर 4–5× महँगे होते हैं।",
  h6="कैसे बचाएँ", tips=["सिस्टम प्रॉम्प्ट और स्थायी निर्देश अंग्रेज़ी में लिखें; सिर्फ़ यूज़र का इनपुट हिन्दी में रहने दें।", "बीच के चरण (क्लासिफ़िकेशन, एक्सट्रैक्शन, टूल कॉल) अंग्रेज़ी या JSON में लें, सिर्फ़ अंतिम जवाब हिन्दी में।", "प्रॉम्प्ट के स्थायी हिस्से के लिए प्रॉम्प्ट कैशिंग इस्तेमाल करें।"],
  h7="सीमाएँ", limits=["सिर्फ़ एक प्रॉम्प्ट मापा गया; दूसरे टेक्स्ट में अनुपात ±0.1–0.2 बदल सकता है।", "Claude और Gemini के टोकनाइज़र अलग हैं; ये आँकड़े सिर्फ़ OpenAI मॉडलों पर लागू हैं।", "अनुवाद जाँचे गए मशीन अनुवाद पर आधारित है।"],
  full="सभी 27 भाषाओं के नतीजे (अंग्रेज़ी में): [27 भाषाओं की तुलना]({enlink})"),
"id": dict(slug="token-bahasa-indonesia-gpt", L="bahasa Indonesia", dec=",",
  title="Bahasa Indonesia memakai 1,15× token bahasa Inggris di GPT",
  desc="Prompt yang sama diukur dalam 27 bahasa: bahasa Indonesia 1,15× token bahasa Inggris. Alasannya dan cara berhemat.",
  cta="Ukur teks Anda sendiri: berapa token dan biaya prompt bahasa Indonesia Anda dibanding bahasa Inggris.", btn="Buka penghitung token",
  h1="Cara mengukur", intro="Saya menerjemahkan prompt layanan pelanggan yang sama ke 27 bahasa dan menghitung token dengan o200k_base, tokenizer OpenAI saat ini (GPT-4o dan setelahnya). Bahasa Inggris butuh {en} token, bahasa Indonesia **{o} token — {ro}× bahasa Inggris**, peringkat {rank} dari {total} (1 = paling murah).",
  plabel="Versi bahasa Indonesia:", h2="Hasil", th=("Bahasa", "Token", "Dibanding bahasa Inggris", "Tokenizer GPT-4 lama"),
  h3="Mengapa", why="Tokenizer terutama belajar dari teks bahasa Inggris: kata seperti \" polite\" atau \" customer\" hanya satu token, sedangkan kata berimbuhan dalam bahasa Indonesia dipecah:",
  h4="Dibanding tokenizer lama", old="Di tokenizer era GPT-4 (cl100k), prompt yang sama **{rc}×**; sekarang **{ro}×**. Bahasa Indonesia termasuk yang paling hemat setelah bahasa Inggris dan Mandarin.",
  h5="Dalam uang", cost="Dengan model seharga $2 per 1 juta token input, mengirim prompt ini 1 juta kali menghabiskan ${encost} dalam bahasa Inggris dan ${cost} dalam bahasa Indonesia. Jika jawabannya juga berbahasa Indonesia, pengali yang sama berlaku untuk token output yang biasanya 4–5× lebih mahal.",
  h6="Cara berhemat", tips=["Tulis system prompt dan instruksi tetap dalam bahasa Inggris; biarkan hanya input pengguna dalam bahasa Indonesia.", "Minta langkah perantara (klasifikasi, ekstraksi, pemanggilan tool) dalam bahasa Inggris atau JSON, dan hanya jawaban akhir dalam bahasa Indonesia.", "Gunakan prompt caching untuk bagian prompt yang tetap."],
  h7="Batasan", limits=["Hanya satu prompt yang diukur; pada teks lain rasionya bisa berbeda ±0,1–0,2.", "Claude dan Gemini memakai tokenizer lain; angka ini hanya berlaku untuk model OpenAI.", "Terjemahan didasarkan pada terjemahan mesin yang sudah diperiksa."],
  full="Hasil lengkap 27 bahasa (dalam bahasa Inggris): [perbandingan 27 bahasa]({enlink})"),
"vi": dict(slug="token-tieng-viet-gpt", L="tiếng Việt", dec=",",
  title="Tiếng Việt dùng gấp 1,35 lần token so với tiếng Anh trong GPT",
  desc="Đo cùng một prompt bằng 27 ngôn ngữ: tiếng Việt 1,35× token tiếng Anh (trước đây 2,32×). Lý do và cách tiết kiệm.",
  cta="Đo văn bản của bạn: prompt tiếng Việt tốn bao nhiêu token và tiền so với tiếng Anh.", btn="Mở công cụ đếm token",
  h1="Cách đo", intro="Tôi dịch cùng một prompt chăm sóc khách hàng sang 27 ngôn ngữ và đếm token bằng o200k_base, tokenizer hiện tại của OpenAI (GPT-4o trở về sau). Tiếng Anh cần {en} token, tiếng Việt **{o} token — gấp {ro} lần**, đứng thứ {rank}/{total} (1 = rẻ nhất).",
  plabel="Bản tiếng Việt:", h2="Kết quả", th=("Ngôn ngữ", "Token", "So với tiếng Anh", "Tokenizer GPT-4 cũ"),
  h3="Vì sao", why="Tokenizer học chủ yếu từ văn bản tiếng Anh: những từ như \" polite\" hay \" customer\" chỉ là một token, còn chữ tiếng Việt có dấu thường bị tách ra:",
  h4="So với tokenizer cũ", old="Với tokenizer thời GPT-4 (cl100k), cùng prompt này gấp **{rc}×**; nay chỉ còn **{ro}×**.",
  h5="Quy ra tiền", cost="Với mô hình giá 2 $ cho 1 triệu token đầu vào, gửi prompt này 1 triệu lần tốn {encost} $ bằng tiếng Anh và {cost} $ bằng tiếng Việt. Nếu câu trả lời cũng bằng tiếng Việt, hệ số này áp dụng cả cho token đầu ra, vốn thường đắt gấp 4–5 lần.",
  h6="Cách tiết kiệm", tips=["Viết system prompt và hướng dẫn cố định bằng tiếng Anh; chỉ giữ tiếng Việt cho phần người dùng nhập.", "Yêu cầu các bước trung gian (phân loại, trích xuất, gọi công cụ) bằng tiếng Anh hoặc JSON, chỉ câu trả lời cuối bằng tiếng Việt.", "Dùng prompt caching cho phần cố định của prompt."],
  h7="Giới hạn", limits=["Chỉ đo một prompt; với văn bản khác tỉ lệ có thể lệch ±0,1–0,2.", "Claude và Gemini dùng tokenizer khác; các con số chỉ đúng với mô hình OpenAI.", "Bản dịch dựa trên dịch máy đã được kiểm tra."],
  full="Kết quả đầy đủ 27 ngôn ngữ (tiếng Anh): [so sánh 27 ngôn ngữ]({enlink})"),
"th": dict(slug="token-phasa-thai-gpt", L="ภาษาไทย", dec=".",
  title="ภาษาไทยใช้โทเค็นมากกว่าภาษาอังกฤษ 1.74 เท่าใน GPT",
  desc="วัดพรอมต์เดียวกันใน 27 ภาษา: ภาษาไทยใช้ 1.74× ของภาษาอังกฤษ (เดิม 3.71×) สาเหตุและวิธีประหยัด",
  cta="ลองวัดข้อความของคุณเอง: พรอมต์ภาษาไทยใช้โทเค็นและค่าใช้จ่ายมากกว่าภาษาอังกฤษเท่าไร", btn="เปิดตัวนับโทเค็น",
  h1="วิธีวัด", intro="เราแปลพรอมต์บริการลูกค้าเดียวกันเป็น 27 ภาษา แล้วนับโทเค็นด้วย o200k_base ซึ่งเป็นตัวตัดคำ (tokenizer) ปัจจุบันของ OpenAI (GPT-4o ขึ้นไป) ภาษาอังกฤษใช้ {en} โทเค็น ภาษาไทยใช้ **{o} โทเค็น หรือ {ro} เท่า** อยู่อันดับ {rank} จาก {total} (1 = ถูกที่สุด)",
  plabel="ฉบับภาษาไทย:", h2="ผลลัพธ์", th=("ภาษา", "โทเค็น", "เทียบกับภาษาอังกฤษ", "tokenizer GPT-4 รุ่นเก่า"),
  h3="ทำไม", why="tokenizer เรียนรู้จากข้อความภาษาอังกฤษเป็นหลัก คำอย่าง \" polite\" หรือ \" customer\" เป็นโทเค็นเดียว แต่ภาษาไทยที่ไม่เว้นวรรคระหว่างคำมักถูกตัดเป็นชิ้นเล็ก ๆ:",
  h4="เทียบกับ tokenizer รุ่นเก่า", old="ใน tokenizer ยุค GPT-4 (cl100k) พรอมต์เดียวกันใช้ **{rc}×** ตอนนี้เหลือ **{ro}×** ค่าใช้จ่ายลดลงกว่าครึ่ง",
  h5="คิดเป็นเงิน", cost="กับโมเดลราคา 2 ดอลลาร์ต่อ 1 ล้านโทเค็นขาเข้า การส่งพรอมต์นี้ 1 ล้านครั้งเป็นภาษาอังกฤษใช้ {encost} ดอลลาร์ ภาษาไทยใช้ {cost} ดอลลาร์ หากคำตอบเป็นภาษาไทยด้วย ตัวคูณเดียวกันจะมีผลกับโทเค็นขาออกซึ่งมักแพงกว่า 4–5 เท่า",
  h6="วิธีประหยัด", tips=["เขียน system prompt และคำสั่งที่ใช้ซ้ำเป็นภาษาอังกฤษ ให้เหลือภาษาไทยเฉพาะข้อความจากผู้ใช้", "ให้ขั้นตอนกลาง (จัดหมวดหมู่ ดึงข้อมูล เรียกเครื่องมือ) ตอบเป็นภาษาอังกฤษหรือ JSON และให้เฉพาะคำตอบสุดท้ายเป็นภาษาไทย", "ใช้ prompt caching กับส่วนของพรอมต์ที่คงที่"],
  h7="ข้อจำกัด", limits=["วัดเพียงพรอมต์เดียว ข้อความอื่นอาจต่างได้ ±0.1–0.2", "Claude และ Gemini ใช้ tokenizer ต่างกัน ตัวเลขนี้ใช้กับโมเดลของ OpenAI เท่านั้น", "คำแปลมาจากการแปลด้วยเครื่องที่ตรวจทานแล้ว"],
  full="ผลครบทั้ง 27 ภาษา (ภาษาอังกฤษ): [เปรียบเทียบ 27 ภาษา]({enlink})"),
"nl": dict(slug="tokens-nederlands-gpt", L="het Nederlands", dec=",",
  title="Nederlands kost in GPT 1,29× zoveel tokens als Engels",
  desc="Dezelfde prompt in 27 talen gemeten: Nederlands gebruikt 1,29× de tokens van Engels. Waarom en hoe je bespaart.",
  cta="Meet je eigen tekst: hoeveel tokens en geld je Nederlandse prompt kost vergeleken met Engels.", btn="Tokenteller openen",
  h1="Zo heb ik gemeten", intro="Ik vertaalde dezelfde klantenservice-prompt naar 27 talen en telde de tokens met o200k_base, de huidige tokenizer van OpenAI (GPT-4o en nieuwer). Engels heeft {en} tokens nodig, Nederlands **{o} — {ro}× zoveel**, plaats {rank} van {total} (1 = goedkoopst).",
  plabel="De Nederlandse versie:", h2="Resultaten", th=("Taal", "Tokens", "Ten opzichte van Engels", "Oude GPT-4-tokenizer"),
  h3="Waarom", why="De tokenizer leert vooral van Engelse tekst: woorden als \" polite\" of \" customer\" zijn één token, terwijl veel Nederlandse woorden in stukken worden gehakt:",
  h4="Vergeleken met de oude tokenizer", old="Met de tokenizer uit het GPT-4-tijdperk (cl100k) kostte dezelfde prompt **{rc}×**, nu **{ro}×**.",
  h5="In geld", cost="Bij een model van $2 per miljoen inputtokens kost het {encost} dollar in het Engels en {cost} dollar in het Nederlands om deze prompt een miljoen keer te versturen. Antwoordt het model ook in het Nederlands, dan geldt dezelfde factor voor de outputtokens, die meestal 4–5× duurder zijn.",
  h6="Zo bespaar je", tips=["Schrijf de systeemprompt en vaste instructies in het Engels; houd alleen de invoer van gebruikers in het Nederlands.", "Laat tussenstappen (classificatie, extractie, tool-aanroepen) in het Engels of als JSON teruggeven, en alleen het eindantwoord in het Nederlands.", "Gebruik prompt caching voor het vaste deel van de prompt."],
  h7="Beperkingen", limits=["Er is één prompt gemeten; bij andere teksten kan de verhouding ±0,1–0,2 afwijken.", "Claude en Gemini gebruiken andere tokenizers; deze cijfers gelden alleen voor OpenAI-modellen.", "De vertaling is gebaseerd op een gecontroleerde machinevertaling."],
  full="Alle resultaten voor 27 talen (in het Engels): [vergelijking van 27 talen]({enlink})"),
"bn": dict(slug="token-bangla-gpt", L="বাংলা", dec=".",
  title="GPT-তে বাংলায় ইংরেজির চেয়ে 1.68× টোকেন লাগে",
  desc="একই প্রম্পট ২৭টি ভাষায় মাপা: বাংলা এখন 1.68×, পুরোনো GPT-4 টোকেনাইজারে ছিল 6.09×। কারণ ও সাশ্রয়ের উপায়।",
  cta="নিজের লেখা মেপে দেখুন: আপনার বাংলা প্রম্পট ইংরেজির তুলনায় কত টোকেন ও কত খরচ নেয়।", btn="টোকেন কাউন্টার খুলুন",
  h1="কীভাবে মাপা হলো", intro="একই কাস্টমার-সাপোর্ট প্রম্পট ২৭টি ভাষায় অনুবাদ করে OpenAI-এর বর্তমান o200k_base টোকেনাইজার (GPT-4o ও পরের মডেল) দিয়ে টোকেন গোনা হয়েছে। ইংরেজিতে লাগে {en} টোকেন, বাংলায় **{o} টোকেন — ইংরেজির {ro}×**; {total}টি ভাষার মধ্যে সবচেয়ে সস্তা থেকে গুনলে {rank} নম্বরে।",
  plabel="বাংলা সংস্করণ:", h2="ফলাফল", th=("ভাষা", "টোকেন", "ইংরেজির তুলনায়", "পুরোনো GPT-4 টোকেনাইজার"),
  h3="কেন", why="টোকেনাইজার মূলত ইংরেজি লেখা থেকে শেখে: \" polite\" বা \" customer\"-এর মতো শব্দ একটিই টোকেন, কিন্তু অনেক বাংলা শব্দ কার-চিহ্নসহ টুকরো হয়ে যায়:",
  h4="পুরোনো টোকেনাইজারের সঙ্গে তুলনা", old="GPT-4 যুগের টোকেনাইজারে (cl100k) একই প্রম্পট ছিল **{rc}×**, এখন **{ro}×**। অর্থাৎ বাংলার খরচ প্রায় চার ভাগের এক ভাগে নেমেছে — ২৭টি ভাষার মধ্যে সবচেয়ে বড় উন্নতি।",
  h5="টাকার হিসাবে", cost="প্রতি ১০ লাখ ইনপুট টোকেনে ২ ডলারের একটি মডেলে এই প্রম্পট ১০ লাখ বার পাঠাতে ইংরেজিতে {encost} ডলার আর বাংলায় {cost} ডলার খরচ হয়। উত্তরও বাংলায় হলে একই গুণক আউটপুট টোকেনেও লাগে, যা সাধারণত ৪–৫ গুণ দামি।",
  h6="কীভাবে সাশ্রয় করবেন", tips=["সিস্টেম প্রম্পট ও স্থায়ী নির্দেশনা ইংরেজিতে লিখুন; শুধু ব্যবহারকারীর ইনপুট বাংলায় রাখুন।", "মাঝের ধাপগুলো (শ্রেণিবিন্যাস, তথ্য বের করা, টুল কল) ইংরেজি বা JSON-এ নিন, শুধু শেষ উত্তর বাংলায়।", "প্রম্পটের স্থায়ী অংশে প্রম্পট ক্যাশিং ব্যবহার করুন।"],
  h7="সীমাবদ্ধতা", limits=["একটিমাত্র প্রম্পট মাপা হয়েছে; অন্য লেখায় অনুপাত ±0.1–0.2 বদলাতে পারে।", "Claude ও Gemini-এর টোকেনাইজার আলাদা; এই সংখ্যাগুলো শুধু OpenAI মডেলের জন্য।", "অনুবাদ যাচাই করা মেশিন অনুবাদের ওপর ভিত্তি করে।"],
  full="২৭টি ভাষার পূর্ণ ফলাফল (ইংরেজিতে): [২৭ ভাষার তুলনা]({enlink})"),
"ur": dict(slug="token-urdu-gpt", L="اردو", dec=".",
  title="GPT میں اردو، انگریزی سے 1.59 گنا زیادہ ٹوکن لیتی ہے",
  desc="ایک ہی پرامپٹ 27 زبانوں میں ناپا: اردو اب 1.59× ہے، پرانے GPT-4 ٹوکنائزر پر 4.24× تھی۔ وجہ اور بچت کے طریقے۔",
  cta="اپنا متن ناپیں: آپ کا اردو پرامپٹ انگریزی کے مقابلے میں کتنے ٹوکن اور کتنا خرچ لیتا ہے۔", btn="ٹوکن کاؤنٹر کھولیں",
  h1="کیسے ناپا", intro="ہم نے ایک ہی کسٹمر سپورٹ پرامپٹ کا 27 زبانوں میں ترجمہ کیا اور OpenAI کے موجودہ o200k_base ٹوکنائزر (‏GPT-4o اور بعد کے ماڈل) سے ٹوکن گنے۔ انگریزی میں {en} ٹوکن لگتے ہیں اور اردو میں **{o} ٹوکن، یعنی انگریزی کا {ro}×**؛ {total} زبانوں میں سب سے سستی سے گنیں تو {rank} واں نمبر۔",
  plabel="اردو ورژن:", h2="نتائج", th=("زبان", "ٹوکن", "انگریزی کے مقابلے میں", "پرانا GPT-4 ٹوکنائزر"),
  h3="کیوں", why="ٹوکنائزر زیادہ تر انگریزی متن سے سیکھتا ہے: \" polite\" یا \" customer\" جیسے الفاظ ایک ٹوکن ہوتے ہیں، جبکہ بہت سے اردو الفاظ ٹکڑوں میں بٹ جاتے ہیں:",
  h4="پرانے ٹوکنائزر سے موازنہ", old="GPT-4 دور کے ٹوکنائزر (cl100k) پر یہی پرامپٹ **{rc}×** تھا؛ اب **{ro}×** ہے۔",
  h5="پیسوں میں", cost="ہر 10 لاکھ ان پٹ ٹوکن پر 2 ڈالر والے ماڈل میں یہ پرامپٹ 10 لاکھ بار بھیجنے پر انگریزی میں {encost} ڈالر اور اردو میں {cost} ڈالر لگتے ہیں۔ جواب بھی اردو میں ہو تو یہی ضرب آؤٹ پٹ ٹوکنز پر بھی لگتی ہے جو عموماً 4–5 گنا مہنگے ہوتے ہیں۔",
  h6="کیسے بچت کریں", tips=["سسٹم پرامپٹ اور مستقل ہدایات انگریزی میں لکھیں؛ صرف صارف کا ان پٹ اردو میں رکھیں۔", "درمیانی مراحل (درجہ بندی، معلومات نکالنا، ٹول کال) انگریزی یا JSON میں لیں، صرف آخری جواب اردو میں۔", "پرامپٹ کے مستقل حصے کے لیے پرامپٹ کیشنگ استعمال کریں۔"],
  h7="حدود", limits=["صرف ایک پرامپٹ ناپا گیا؛ دوسرے متن میں تناسب ±0.1–0.2 بدل سکتا ہے۔", "Claude اور Gemini کے ٹوکنائزر مختلف ہیں؛ یہ اعداد صرف OpenAI ماڈلز کے لیے ہیں۔", "ترجمہ جانچے گئے مشینی ترجمے پر مبنی ہے۔"],
  full="تمام 27 زبانوں کے نتائج (انگریزی میں): [27 زبانوں کا موازنہ]({enlink})"),
"fil": dict(slug="token-filipino-gpt", L="Filipino", dec=".",
  title="Gumagamit ang Filipino ng 1.53× na token kumpara sa English sa GPT",
  desc="Sinukat ang parehong prompt sa 27 wika: Filipino ay 1.53× ng token ng English. Bakit at paano makatipid.",
  cta="Sukatin ang sarili mong text: ilang token at magkano ang prompt mo sa Filipino kumpara sa English.", btn="Buksan ang token counter",
  h1="Paano sinukat", intro="Isinalin ko ang parehong customer-support prompt sa 27 wika at binilang ang token gamit ang o200k_base, ang kasalukuyang tokenizer ng OpenAI (GPT-4o at mas bago). Sa English, {en} token; sa Filipino, **{o} token — {ro}× ng English**, ika-{rank} sa {total} (1 = pinakamura).",
  plabel="Ang bersyong Filipino:", h2="Mga resulta", th=("Wika", "Token", "Kumpara sa English", "Lumang GPT-4 tokenizer"),
  h3="Bakit", why="Karamihang natututo ang tokenizer mula sa English na text: isang token lang ang mga salitang tulad ng \" polite\" o \" customer\", pero hinahati-hati ang maraming salitang Filipino na may panlapi:",
  h4="Kumpara sa lumang tokenizer", old="Sa tokenizer ng panahon ng GPT-4 (cl100k), **{rc}×** ang parehong prompt; ngayon **{ro}×**.",
  h5="Sa pera", cost="Sa model na $2 bawat 1 milyong input token, ang pagpapadala ng prompt na ito nang 1 milyong beses ay ${encost} sa English at ${cost} sa Filipino. Kung Filipino rin ang sagot, parehong multiplier ang tatama sa output token, na kadalasang 4–5× na mas mahal.",
  h6="Paano makatipid", tips=["Isulat sa English ang system prompt at mga nakapirming tagubilin; Filipino lang ang input ng user.", "Hilingin sa English o JSON ang mga pansamantalang hakbang (classification, extraction, tool call), at Filipino lang ang huling sagot.", "Gumamit ng prompt caching para sa nakapirming bahagi ng prompt."],
  h7="Mga limitasyon", limits=["Isang prompt lang ang sinukat; sa ibang text, maaaring mag-iba ang ratio ng ±0.1–0.2.", "Iba ang tokenizer ng Claude at Gemini; para lang sa mga OpenAI model ang mga numerong ito.", "Batay ang salin sa sinuring machine translation."],
  full="Buong resulta ng 27 wika (sa English): [paghahambing ng 27 wika]({enlink})"),
"sv": dict(slug="tokens-svenska-gpt", L="svenska", dec=",",
  title="Svenska kostar 1,32× så många tokens som engelska i GPT",
  desc="Samma prompt mätt på 27 språk: svenska använder 1,32× tokens jämfört med engelska. Varför och hur du sparar.",
  cta="Mät din egen text: hur många tokens och hur mycket pengar din svenska prompt kostar jämfört med engelska.", btn="Öppna tokenräknaren",
  h1="Så mätte jag", intro="Jag översatte samma kundtjänstprompt till 27 språk och räknade tokens med o200k_base, OpenAI:s nuvarande tokenizer (GPT-4o och senare). Engelska behöver {en} tokens, svenska **{o} — {ro}× så många**, plats {rank} av {total} (1 = billigast).",
  plabel="Den svenska versionen:", h2="Resultat", th=("Språk", "Tokens", "Jämfört med engelska", "Gamla GPT-4-tokenizern"),
  h3="Varför", why="Tokenizern lär sig mest från engelsk text: ord som \" polite\" eller \" customer\" är en enda token, medan många svenska ord – särskilt sammansättningar – delas upp:",
  h4="Jämfört med den gamla tokenizern", old="Med tokenizern från GPT-4-eran (cl100k) kostade samma prompt **{rc}×**, i dag **{ro}×**.",
  h5="I pengar", cost="Med en modell för 2 $ per miljon input-tokens kostar det {encost} $ på engelska och {cost} $ på svenska att skicka prompten en miljon gånger. Svarar modellen också på svenska gäller samma faktor för output-tokens, som oftast är 4–5× dyrare.",
  h6="Så sparar du", tips=["Skriv systemprompten och fasta instruktioner på engelska; låt bara användarens input vara på svenska.", "Be om mellansteg (klassificering, extraktion, verktygsanrop) på engelska eller som JSON, och bara slutsvaret på svenska.", "Använd prompt caching för den fasta delen av prompten."],
  h7="Begränsningar", limits=["En enda prompt mättes; för andra texter kan kvoten skilja ±0,1–0,2.", "Claude och Gemini har andra tokenizers – siffrorna gäller bara OpenAI-modeller.", "Översättningen bygger på en granskad maskinöversättning."],
  full="Alla resultat för 27 språk (på engelska): [jämförelse av 27 språk]({enlink})"),
"he": dict(slug="tokens-ivrit-gpt", L="עברית", dec=".",
  title="עברית ב-GPT צורכת פי 1.56 יותר טוקנים מאנגלית",
  desc="מדדנו את אותו פרומפט ב-27 שפות: עברית 1.56× מטוקני האנגלית (בעבר 3.76×). למה ואיך לחסוך.",
  cta="מדדו את הטקסט שלכם: כמה טוקנים וכמה כסף עולה הפרומפט שלכם בעברית לעומת אנגלית.", btn="פתיחת מונה הטוקנים",
  h1="איך מדדנו", intro="תרגמנו את אותו פרומפט של שירות לקוחות ל-27 שפות וספרנו טוקנים עם o200k_base, הטוקנייזר הנוכחי של OpenAI ‏(GPT-4o ואילך). באנגלית נדרשים {en} טוקנים, בעברית **{o} — פי {ro}**, מקום {rank} מתוך {total} (1 = הזול ביותר).",
  plabel="הגרסה העברית:", h2="תוצאות", th=("שפה", "טוקנים", "ביחס לאנגלית", "הטוקנייזר הישן של GPT-4"),
  h3="למה", why="הטוקנייזר לומד בעיקר מטקסט באנגלית: מילים כמו \" polite\" או \" customer\" הן טוקן אחד, בעוד שמילים רבות בעברית, עם תחיליות וסיומות, מתפרקות לחלקים:",
  h4="לעומת הטוקנייזר הישן", old="בטוקנייזר מתקופת GPT-4 ‏(cl100k) אותו פרומפט היה **{rc}×**, והיום **{ro}×** — פחות מחצי.",
  h5="בכסף", cost="במודל שעולה 2 דולר למיליון טוקני קלט, שליחת הפרומפט מיליון פעמים עולה {encost} דולר באנגלית ו-{cost} דולר בעברית. אם גם התשובה בעברית, אותו מכפיל חל על טוקני הפלט, שעולים בדרך כלל פי 4–5.",
  h6="איך לחסוך", tips=["כתבו את פרומפט המערכת וההוראות הקבועות באנגלית, והשאירו בעברית רק את קלט המשתמש.", "בקשו את שלבי הביניים (סיווג, חילוץ, קריאות לכלים) באנגלית או ב-JSON, ורק את התשובה הסופית בעברית.", "השתמשו ב-Prompt Caching לחלק הקבוע של הפרומפט."],
  h7="מגבלות", limits=["נמדד פרומפט אחד; בטקסטים אחרים היחס עשוי להשתנות ב-±0.1–0.2.", "ל-Claude ול-Gemini יש טוקנייזרים אחרים; המספרים נכונים רק למודלים של OpenAI.", "התרגום מבוסס על תרגום מכונה שנבדק."],
  full="התוצאות המלאות ל-27 שפות (באנגלית): [השוואה של 27 שפות]({enlink})"),
}
