# -*- coding: utf-8 -*-
"""Czech (cs) strings for the AI game cost calculator + Roblox block. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same value as gamecost_i18n.CHECKED (defined there, not imported to avoid cycles)

GC = dict(
  title="Kolik stojí vytvořit hru s AI?", desc="Spočítej náklady, čas a prompty pro AI hru podle žánru, velikosti a platformy.",
  badge="Nové · zdarma · bez registrace", h1="Kalkulačka nákladů na hru s AI",
  sub="Odpověz na pár otázek o své 2D hře. Dostaneš seznam assetů, náklady a čas na vytvoření s AI nástroji, počet tokenů a balíček promptů, se kterým můžeš začít ještě dnes.",
  qProject="Tvoje hra", name="Název hry", namePh="např. Kočičí kavárna Merge", idea="Nápad v jedné větě", ideaPh="např. spojuj kočičí nábytek a zařiď kavárnu",
  qGenre="Žánr", qScale="Velikost", sS="Malá", sSsub="≈ 2 týdny sám", sM="Střední", sMsub="≈ 4 týdny", sL="Velká", sLsub="≈ 6 týdnů", sXL="Velmi velká", sXLsub="≈ 3 měsíce a víc",
  qStyle="Grafický styl", stPixel="Pixel art", stIllust="Ilustrace", stSimple="Jednoduchý / vektor",
  qDim="Zobrazení", d2="2D", d3="2.5D / 3D modely",
  qChars="Postavy / nepřátelé", qAnim="Animace", aNone="Žádná", aSimple="Jednoduchá (3 pohyby)", aFull="Plná (6 pohybů)",
  qMusic="Hudební skladby", qSfx="Zvukové efekty", sfFew="Málo", sfNormal="Běžně", sfMany="Hodně", qVoice="Namluvené repliky",
  qFeats="Funkce", qLangs="Jazyky", qEngine="Engine", qTrailer="Propagační trailer", yes="Ano", no="Ne",
  qTools="Tvoje nástroje", qImg="Obrázky", qCode="Programování", qMusicTool="Hudba", qSfxTool="Zvukové efekty", q3dTool="3D modely (u 2.5D / 3D)", freeLib="Bezplatné knihovny", freeMusic="Pixabay (zdarma)", qModel="Model API",
  resTitle="Co tvoje hra potřebuje", cmpTitle="Náklady a čas s AI",
  promptTitle="Tvůj balíček promptů", promptSub="Vytvořeno z tvých odpovědí. Prompty pro assety jsou v angličtině, protože nástroje na obrázky, hudbu a zvuky fungují nejlépe anglicky.",
  tDev="Start vývoje", tArt="Grafika", tMusic="Hudba", tSfx="Zvukové efekty", tTrailer="Trailer", copy="Kopírovat", download="Stáhnout vše (.md)",
  howTitle="Jak to odhadujeme",
  how=["Velikosti vycházejí ze skutečných her, které vytvořil jeden člověk s AI kódovacími agenty: malá mobilní hra trvala asi 2 týdny, střední asi 4 a velká asi 6; velmi velká asi 3 měsíce. Žánr, funkce, jazyky a 3D tato čísla mění.",
       "Obrázky = postavy × snímky animace + pozadí + předměty + UI. Počítáme s tím, že si necháš zhruba 1 ze 3 generování, takže generování je třikrát víc než obrázků.",
       "Kódovací tokeny předpokládají agenta jako Claude Code, který pracuje asi 70 % dní a denně přečte kolem 20 milionů tokenů, většinou z cache. Náklady API používají aktuální ceníkovou cenu zvoleného modelu; předplatné se počítá po měsících."],
  srcTitle="Použité ceny nástrojů", srcNote=f"Ověřeno {CHECKED}. Ceny se často mění – před nákupem si zkontroluj ceník každého nástroje.",
  faqTitle="Časté otázky",
  faq=[("Kolik stojí vytvořit 2D hru s AI?", "U malé mobilní hry utratí jeden člověk s AI nástroji obvykle asi 100–300 $ za předplatné a API a zabere mu to 2–3 týdny. Svůj žánr a velikost si spočítej v kalkulačce výše."),
       ("Jaké AI nástroje potřebuji k vytvoření hry?", "Obvykle čtyři: nástroj na obrázky pro sprity a pozadí (Midjourney, Leonardo, Gemini, PixelLab, Scenario nebo obrázkové API), nástroj na hudbu (Suno, Stable Audio, AIVA nebo bezplatná hudba z Pixabay), nástroj na zvukové efekty (ElevenLabs, Stable Audio nebo bezplatné knihovny) a kódovacího agenta (Claude Code, Cursor nebo Gemini CLI). Meshy pomůže s 3D modely, Higgsfield s propagačním videem."),
       ("Kolik tokenů stojí naprogramovat hru s Claude Code?", "Agenti tvůj projekt pořád znovu čtou, takže dvoutýdenní vývoj může dosáhnout několika set milionů tokenů, většinou z cache. S Claude Max platíš pevnou částku měsíčně; u API ukáže kalkulačka cenu zvoleného modelu."),
       ("Můžu prompty volně používat?", "Ano. Zkopíruj je nebo si stáhni celý balíček jako soubor Markdown a vlož je do svých nástrojů. Nic z toho, co zadáš, se nikam nenahrává.")],
  defName="Moje hra", defIdea="hra žánru {genre} pro {plat}",
  g_merge="Merge", g_puzzle="Logická", g_racing="Závodní", g_idle="Idle", g_platformer="Plošinovka", g_rpg="RPG", g_novel="Vizuální román", g_shooter="Střílečka", g_match3="Match-3", g_tower="Tower defense", g_card="Karetní / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / budovatelská", g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Rytmická", g_word="Slovní / kvíz", g_farming="Farma / simulace života", g_escape="Úniková hra / hledání předmětů", g_board="Desková hra", g_autobattler="Auto battler", g_survival="Survival / crafting", g_fishing="Rybaření", g_sports="Sportovní", g_fighting="Bojovka", g_pet="Péče o mazlíčky", g_minigames="Sbírka minihier", g_metroidvania="Metroidvania", g_strategy="Strategie / 4X", g_gacha="Gacha sběratelské RPG", g_horror="Horor", g_sandbox="Sandbox", g_mmo="MMO / online RPG", gOther="Další ▾",
  f_ads="Reklamy", f_iap="Nákupy v aplikaci", f_save="Ukládání / načítání", f_rank="Žebříček", f_online="Online multiplayer",
  devIntro="Jsi zkušený vývojář her. Pomoz mi vytvořit \"{name}\", 2D hru žánru {genre} pro {plat} v enginu {engine}.",
  qPlat="Vychází na", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web", pls_android="Google Play, jednorázově", pls_mobile="Google Play $25 + Apple $99/rok", pls_pc="Steam Direct, za hru", pls_web="", l_store="Poplatky obchodu", l_server="Server",
  devIdea="Nápad:", devScope="Rozsah: {chars} postav, {bg} pozadí, {items} předmětů, {music} hudebních skladeb, {sfx} zvukových efektů, {langs} jazyk(ů).",
  devFeats="Funkce:", devRules="Pravidla: drž kód jednoduchý a modulární; jedna funkce na krok; po každém kroku mi řekni, jak ho otestovat na telefonu; používej zástupné tvary, dokud ti nedám skutečnou grafiku.",
  devSteps="Postav to v těchto krocích:", st1="Nastavení projektu, struktura složek, tok scén (titulek → hra → výsledek)", st2="Hlavní herní smyčka se zástupnou grafikou",
  st3="Skóre, postup a křivka obtížnosti", st4="UI: menu, HUD, pauza, nastavení", st5="Přidat: {feats}", st6="Vložit finální grafiku, hudbu a zvukové efekty", st7="Doladění, kontrola výkonu a build pro Android",
  devStart="Začni krokem 1. Než začneš psát kód, zeptej se mě na vše, co potřebuješ.",
  rImages="Obrázky", rImagesSub="{chars} postav · {frames} snímků · {bg} pozadí · {items} předmětů · {ui} UI", rAudio="Hudba + zvuky", rAudioSub="skladby + efekty",
  rCode="Řádky kódu", rCodeSub="odhad", rTokens="Kódovací tokeny", rTokensSub="≈ {api} přes API",
  l_art="Grafika", l_music="Hudba", l_sfx="Zvuk / hlas", l_code="Kód", l_d3="3D modely", l_trailer="Trailer",
  p_value="💰 Nejvýhodnější", p_normal="⚖️ Standard", p_max="🚀 Špička", pCustom="Tvoje kombinace", tier_value="levné", tier_normal="standard", tier_max="prémiové", pHint="Klikni na kombinaci a přepneš všechny nástroje najednou, nebo je níže měň jeden po druhém.",
  days="{n} dní", monthsN="{n} měs.", capWarn="Limit využití tohoto předplatného pravděpodobně nestačí na každodenní kódování s agentem – počítej s čekáním nebo příplatky.",
  qa="Stručně: vytvořit sám malou mobilní 2D hru s AI nástroji trvá asi 2–3 týdny a stojí kolem 50–180 $ za předplatné a API (říjen 2026). Největší část tvoří předplatné AI na kódování.", sumTitle="Náklady a čas podle žánru a velikosti", sumNote="Každá buňka: doba vývoje · náklady od nejvýhodnější po standardní kombinaci. Jeden člověk s AI, USD bez DPH, včetně poplatků obchodu. Ověřeno {date}.",
  cTax="Vč. DPH ({pct} %)", cFx="Kurz ze dne {date}, zaokrouhleno",
  hireRef="Pro srovnání: najmout freelancery na hru této velikosti obvykle začíná na <b>{min}+</b> a nabídky se mohou podle země a kvality lišit i desetkrát a víc.",
  noTrailer="Zapni „Propagační trailer“ a dostaneš prompty pro trailer.",
  copied="Zkopírováno ✓", packTitle="balíček promptů",
  related="Viz také", rel=[("/cs/agents", "Náklady na kódovací agenty"), ("/cs/image", "Cena za AI obrázek"), ("/cs/plans", "Předplatné, nebo API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (vykrádání základen)", g_plus1="+1 za sekundu (útěk / rychlost)", g_verbsim="Simulátor jednoduché činnosti (typ loupání brambor)",
  g_coophorror="Kooperativní horor", g_duels="Souboje 1 na 1", g_rng="RNG / sbírání se štěstím", g_coopobby="Kooperativní obby pro 2",
  rbxTitle="🔥 Teď frčí na Robloxu", rbxSub="Typy her, které stoupají v žebříčcích Robloxu, s počtem současných hráčů. Ověřeno {date} na Roblox Charts.", rbxUse="Použít →",
  rbxMoney="Na Robloxu nejsou žádné poplatky obchodu a servery Roblox provozuje zdarma. Robuxy vyděláváš na game passech a developer products (necháš si 70 %) a z Premium Payouts, a pak je přes DevEx proměníš na peníze za $0,0038 za Robux (minimum 30 000 Robuxů). Příklad: tržby 10 000 Robuxů → 7 000 Robuxů → asi $27.",
  devIntroRbx="Jsi zkušený vývojář pro Roblox. Pomoz mi vytvořit \"{name}\", zážitek žánru {genre} na Robloxu, v Roblox Studiu s Luau.",
  rbxDev="Specifika Robloxu: herní logiku dej do ServerScriptService a UI a vstup klienta do StarterPlayerScripts / StarterGui; ať spolu komunikují jen přes RemoteEvents a nikdy klientovi nevěř. Postup ukládej přes DataStoreService (s opakovanými pokusy). Game passy a developer products prodávej přes MarketplaceService. Na drobné úpravy a 3D modely používej Roblox Assistant ve Studiu a každý krok udělej testovatelný v režimu Play.",
  rbxPublish="Doladit, otestovat ve Studiu se 2+ hráči, nastavit ikonu a náhledy a publikovat na Roblox",
)

NAV = "Cena hry"
