# -*- coding: utf-8 -*-
"""Danish (da) strings for the AI game cost calculator. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same value as gamecost_i18n.CHECKED (copied to avoid importing gamecost modules)

GC = dict(
  title="Hvad koster det at lave et spil med AI?",
  desc="Beregn pris, tid og prompts til dit AI-spil efter genre, størrelse og platform.",
  badge="Nyt · gratis · ingen tilmelding",
  h1="Beregner for spilomkostninger med AI",
  sub="Svar på et par spørgsmål om dit 2D-spil. Du får listen over assets, prisen og tiden for at bygge det med AI-værktøjer, antallet af tokens og en promptpakke, så du kan gå i gang i dag.",
  qProject="Dit spil", name="Spillets navn", namePh="f.eks. Kattecafé Merge", idea="Idéen på én linje", ideaPh="f.eks. sæt kattemøbler sammen og indret en café",
  qGenre="Genre", qScale="Størrelse",
  sS="Lille", sSsub="≈ 2 uger alene", sM="Mellem", sMsub="≈ 4 uger", sL="Stort", sLsub="≈ 6 uger", sXL="Meget stort", sXLsub="≈ 3 måneder eller mere",
  qStyle="Grafisk stil", stPixel="Pixelgrafik", stIllust="Illustration", stSimple="Enkel / vektor",
  qDim="Udseende", d2="2D", d3="2.5D / 3D-modeller",
  qChars="Figurer / fjender", qAnim="Animation", aNone="Ingen", aSimple="Enkel (3 bevægelser)", aFull="Fuld (6 bevægelser)",
  qMusic="Musiknumre", qSfx="Lydeffekter", sfFew="Få", sfNormal="Normalt", sfMany="Mange",
  qVoice="Stemmereplikker", qFeats="Funktioner", qLangs="Sprog", qEngine="Motor", qTrailer="Reklametrailer",
  yes="Ja", no="Nej",
  qTools="Dine værktøjer", qImg="Billeder", qCode="Kode", qMusicTool="Musik", qSfxTool="Lydeffekter", q3dTool="3D-modeller (ved 2.5D / 3D)",
  freeLib="Gratis biblioteker", freeMusic="Pixabay (gratis)", qModel="API-model",
  resTitle="Det her skal dit spil bruge", cmpTitle="Pris og tid med AI",
  promptTitle="Din promptpakke",
  promptSub="Bygget ud fra dine svar. Promptene til assets er på engelsk, fordi billed-, musik- og lydværktøjer fungerer bedst på engelsk.",
  tDev="Udviklingsstart", tArt="Grafik", tMusic="Musik", tSfx="Lydeffekter", tTrailer="Trailer",
  copy="Kopiér", download="Download det hele (.md)",
  howTitle="Sådan regnes estimatet ud",
  how=[
    "Størrelserne bygger på rigtige spil lavet af én person med AI-kodeagenter: et lille mobilspil tog omkring 2 uger, et mellemstort omkring 4 og et stort omkring 6; et meget stort omkring 3 måneder. Genre, funktioner, sprog og 3D ændrer tallene.",
    "Billeder = figurer × animationsframes + baggrunde + genstande + UI. Vi regner med, at du beholder cirka 1 ud af 3 genereringer, så der er tre gange så mange genereringer som billeder.",
    "Kodetokens forudsætter, at en agent som Claude Code arbejder på omkring 70 % af dagene og læser cirka 20 millioner tokens om dagen, mest cachet kontekst. API-prisen bruger den aktuelle listepris for den model, du vælger; abonnementer regnes pr. måned.",
  ],
  srcTitle="Anvendte værktøjspriser", srcNote=f"Tjekket {CHECKED}. Priserne ændrer sig tit – tjek hvert værktøjs prisside, før du køber.",
  faqTitle="Ofte stillede spørgsmål",
  faq=[
    ("Hvad koster det at lave et 2D-spil med AI?",
     "For et lille mobilspil bruger én person med AI-værktøjer typisk omkring 100–300 USD på abonnementer og API og 2–3 ugers arbejde. Regn på din egen genre og størrelse i beregneren ovenfor."),
    ("Hvilke AI-værktøjer skal jeg bruge for at lave et spil?",
     "Som regel fire: et billedværktøj til sprites og baggrunde (Midjourney, Leonardo, Gemini, PixelLab, Scenario eller et billed-API), et musikværktøj (Suno, Stable Audio, AIVA eller gratis musik fra Pixabay), et værktøj til lydeffekter (ElevenLabs, Stable Audio eller gratis biblioteker) og en kodeagent (Claude Code, Cursor eller Gemini CLI). Meshy hjælper, hvis du vil have 3D-modeller, og Higgsfield til en reklamevideo."),
    ("Hvor mange tokens bruger det at kode et spil med Claude Code?",
     "Agenter læser projektet igen og igen, så to ugers byggeri kan nå op på et par hundrede millioner tokens, mest fra cachen. Med Claude Max betaler du et fast beløb om måneden; med API'et viser beregneren prisen for den model, du vælger."),
    ("Må jeg bruge promptene frit?",
     "Ja. Kopiér dem eller download hele pakken som en Markdown-fil, og sæt dem ind i dine værktøjer. Intet af det, du skriver, bliver uploadet."),
  ],
  defName="Mit spil", defIdea="et {genre}-spil til {plat}",
  g_merge="Merge", g_puzzle="Puslespil", g_racing="Racing", g_idle="Idle", g_platformer="Platformspil", g_rpg="RPG", g_novel="Visual novel", g_shooter="Skydespil",
  g_match3="Match-3", g_tower="Tower defense", g_card="Kort / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / management",
  g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Rytme", g_word="Ord / quiz", g_farming="Landbrug / livssimulator",
  g_escape="Escape room / skjulte genstande", g_board="Brætspil", g_autobattler="Auto battler", g_survival="Overlevelse / crafting",
  g_fishing="Fiskeri", g_sports="Sport", g_fighting="Fighting", g_pet="Kæledyrsopdræt", g_minigames="Samling af minispil",
  g_metroidvania="Metroidvania", g_strategy="Strategi / 4X", g_gacha="Gacha-RPG med samlerelementer", g_horror="Gyser",
  g_sandbox="Sandkasse", g_mmo="MMO / online-RPG",
  gOther="Flere ▾",
  f_ads="Reklamer", f_iap="Køb i appen", f_save="Gem / indlæs", f_rank="Rangliste", f_online="Online multiplayer",
  devIntro='Du er en erfaren spiludvikler. Hjælp mig med at bygge "{name}", et 2D-{genre}-spil til {plat} i {engine}.',
  qPlat="Udgives på", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web",
  pls_android="Google Play, én gang", pls_mobile="Google Play 25 USD + Apple 99 USD/år", pls_pc="Steam Direct, pr. spil", pls_web="",
  l_store="Butiksgebyr", l_server="Server",
  devIdea="Idé:",
  devScope="Omfang: {chars} figurer, {bg} baggrunde, {items} genstande, {music} musiknumre, {sfx} lydeffekter, {langs} sprog.",
  devFeats="Funktioner:",
  devRules="Regler: hold koden enkel og modulær; én funktion pr. trin; fortæl mig efter hvert trin, hvordan jeg tester det på mobilen; brug pladsholderformer, indtil jeg giver dig den rigtige grafik.",
  devSteps="Byg det i disse trin:",
  st1="Projektopsætning, mappestruktur, sceneflow (titel → spil → resultat)",
  st2="Grundlæggende spilloop med pladsholdergrafik",
  st3="Point, progression og sværhedskurve",
  st4="UI: menuer, HUD, pause, indstillinger",
  st5="Tilføj: {feats}",
  st6="Sæt rigtig grafik, musik og lydeffekter ind",
  st7="Finpudsning, ydelsestjek og build til Android",
  devStart="Start med trin 1. Spørg mig om alt, du har brug for, før du skriver kode.",
  rImages="Billeder", rImagesSub="{chars} figurer · {frames} frames · {bg} baggrunde · {items} genstande · {ui} UI",
  rAudio="Musik + lyd", rAudioSub="numre + effekter",
  rCode="Kodelinjer", rCodeSub="anslået",
  rTokens="Kodetokens", rTokensSub="≈ {api} via API",
  l_art="Grafik", l_music="Musik", l_sfx="Lyd / stemme", l_code="Kode", l_d3="3D-modeller", l_trailer="Trailer",
  p_value="💰 Mest for pengene", p_normal="⚖️ Standard", p_max="🚀 Topklasse", pCustom="Din kombination",
  tier_value="budget", tier_normal="standard", tier_max="premium",
  pHint="Klik på en kombination for at skifte alle værktøjer på én gang, eller skift dem et ad gangen nedenfor.",
  days="{n} dage", monthsN="{n} md.",
  capWarn="Dette abonnements forbrugsgrænse rækker sandsynligvis ikke til agentkodning hver dag – regn med ventetid eller ekstra forbrug.",
  qa="Kort svar: at lave et lille 2D-mobilspil alene med AI-værktøjer tager omkring 2–3 uger og koster cirka 50–180 USD i abonnementer og API (oktober 2026). Det meste går til AI-kodeabonnementet.",
  sumTitle="Pris og tid pr. genre og størrelse",
  sumNote="Hver celle: udviklingstid · pris fra den billigste til standardkombinationen. Én person med AI, USD ekskl. moms, butiksgebyr inkluderet. Tjekket {date}.",
  cTax="Inkl. moms ({pct} %)",
  cFx="Valutakurs {date}, omtrentlig",
  hireRef="Til sammenligning: at hyre freelancere til et spil i denne størrelse starter typisk ved <b>{min}+</b>, og tilbuddene kan svinge ti gange eller mere afhængigt af land og kvalitet.",
  noTrailer="Slå »Reklametrailer« til for at få trailerprompts.",
  copied="Kopieret ✓",
  packTitle="promptpakke",
  related="Se også",
  rel=[("/da/agents", "Prisberegner for kodeagenter"), ("/da/image", "Pris pr. AI-billede"), ("/da/plans", "Abonnement eller API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (plyndr baser)",
  g_plus1="+1 pr. sekund (flugt / fart)",
  g_verbsim="Simpel handlings-sim (fx skræl kartofler)",
  g_coophorror="Co-op-gyser",
  g_duels="1-mod-1-dueller",
  g_rng="RNG / saml med held",
  g_coopobby="Co-op-obby for 2",
  rbxTitle="🔥 Trender på Roblox lige nu",
  rbxSub="Spiltyper, der stiger på Roblox-listerne, med samtidige spillere. Tjekket {date} på Roblox Charts.",
  rbxUse="Brug →",
  rbxMoney="På Roblox er der intet butiksgebyr, og Roblox kører serverne gratis. Du tjener Robux på game passes og developer products (du beholder 70 %) og på Premium Payouts, og veksler dem via DevEx til 0,0038 USD pr. Robux (mindst 30.000 Robux). Eksempel: 10.000 Robux i salg → 7.000 Robux → cirka 27 USD.",
  devIntroRbx='Du er en erfaren Roblox-udvikler. Hjælp mig med at bygge "{name}", et {genre}-spil på Roblox, i Roblox Studio med Luau.',
  rbxDev="Roblox-specifikt: læg spillogikken i ServerScriptService og klientens UI og input i StarterPlayerScripts / StarterGui; lad dem kun tale sammen via RemoteEvents, og stol aldrig på klienten. Gem fremskridt med DataStoreService (med genforsøg). Sælg game passes og developer products via MarketplaceService. Brug Roblox Assistant i Studio til små ændringer og 3D-modeller, og gør hvert trin testbart i Play-tilstand.",
  rbxPublish="Finpuds, test med 2+ spillere i Studio, sæt ikon og thumbnails, og udgiv på Roblox",
)

NAV = "Spilpris"
