# -*- coding: utf-8 -*-
"""Greek (el) strings for the AI game cost calculator. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same literal as gamecost_i18n.CHECKED (copied to avoid a circular import)

GC = dict(
  title="Πόσο κοστίζει ένα παιχνίδι με AI;", desc="Κόστος, χρόνος και prompts για το AI παιχνίδι σου ανά είδος και πλατφόρμα.",
  badge="Νέο · δωρεάν · χωρίς λογαριασμό", h1="Υπολογιστής κόστους παιχνιδιού με AI",
  sub="Απάντησε σε λίγες ερωτήσεις για το 2D παιχνίδι σου. Θα πάρεις τη λίστα με τα assets, το κόστος και τον χρόνο για να το φτιάξεις με εργαλεία AI, τον αριθμό των tokens και ένα πακέτο prompts για να ξεκινήσεις από σήμερα.",
  qProject="Το παιχνίδι σου", name="Όνομα παιχνιδιού", namePh="π.χ. Cat Café Merge", idea="Η ιδέα σε μία πρόταση", ideaPh="π.χ. συνδύασε έπιπλα για γάτες και διακόσμησε ένα καφέ",
  qGenre="Είδος", qScale="Μέγεθος", sS="Μικρό", sSsub="≈ 2 εβδομάδες μόνος", sM="Μεσαίο", sMsub="≈ 4 εβδομάδες", sL="Μεγάλο", sLsub="≈ 6 εβδομάδες", sXL="Πολύ μεγάλο", sXLsub="≈ 3 μήνες ή περισσότερο",
  qStyle="Γραφικό στυλ", stPixel="Pixel art", stIllust="Εικονογράφηση", stSimple="Απλό / vector",
  qDim="Απεικόνιση", d2="2D", d3="2.5D / 3D μοντέλα",
  qChars="Χαρακτήρες / εχθροί", qAnim="Animation", aNone="Καθόλου", aSimple="Απλό (3 κινήσεις)", aFull="Πλήρες (6 κινήσεις)",
  qMusic="Μουσικά κομμάτια", qSfx="Ηχητικά εφέ", sfFew="Λίγα", sfNormal="Κανονικά", sfMany="Πολλά", qVoice="Φωνητικές ατάκες",
  qFeats="Λειτουργίες", qLangs="Γλώσσες", qEngine="Μηχανή", qTrailer="Promo trailer", yes="Ναι", no="Όχι",
  qTools="Τα εργαλεία σου", qImg="Εικόνες", qCode="Προγραμματισμός", qMusicTool="Μουσική", qSfxTool="Ηχητικά εφέ", q3dTool="3D μοντέλα (για 2.5D / 3D)", freeLib="Δωρεάν βιβλιοθήκες", freeMusic="Pixabay (δωρεάν)", qModel="Μοντέλο API",
  resTitle="Τι χρειάζεται το παιχνίδι σου", cmpTitle="Κόστος και χρόνος με AI",
  promptTitle="Το πακέτο prompts σου", promptSub="Φτιαγμένο από τις απαντήσεις σου. Τα prompts για τα assets είναι στα αγγλικά, γιατί τα εργαλεία εικόνας, μουσικής και ήχου δουλεύουν καλύτερα στα αγγλικά.",
  tDev="Έναρξη ανάπτυξης", tArt="Γραφικά", tMusic="Μουσική", tSfx="Ηχητικά εφέ", tTrailer="Trailer", copy="Αντιγραφή", download="Λήψη όλων (.md)",
  howTitle="Πώς γίνεται η εκτίμηση",
  how=["Τα μεγέθη βασίζονται σε πραγματικά παιχνίδια που έφτιαξε ένα άτομο με AI coding agents: ένα μικρό παιχνίδι για κινητά χρειάστηκε περίπου 2 εβδομάδες, ένα μεσαίο περίπου 4 και ένα μεγάλο περίπου 6· ένα πολύ μεγάλο περίπου 3 μήνες. Το είδος, οι λειτουργίες, οι γλώσσες και το 3D αλλάζουν αυτά τα νούμερα.",
       "Εικόνες = χαρακτήρες × καρέ animation + φόντα + αντικείμενα + UI. Υποθέτουμε ότι κρατάς περίπου 1 στις 3 δημιουργίες, άρα οι δημιουργίες είναι τριπλάσιες από τις εικόνες.",
       "Τα tokens προγραμματισμού υποθέτουν ότι ένας agent όπως το Claude Code δουλεύει περίπου το 70% των ημερών και διαβάζει γύρω στα 20 εκατομμύρια tokens την ημέρα, κυρίως context από την cache. Το κόστος API χρησιμοποιεί την τρέχουσα τιμή καταλόγου του μοντέλου που επέλεξες· οι συνδρομές χρεώνονται ανά μήνα."],
  srcTitle="Τιμές εργαλείων που χρησιμοποιήθηκαν", srcNote=f"Ελέγχθηκε στις {CHECKED}. Οι τιμές αλλάζουν συχνά — έλεγξε τη σελίδα τιμών κάθε εργαλείου πριν αγοράσεις.",
  faqTitle="Συχνές ερωτήσεις",
  faq=[("Πόσο κοστίζει να φτιάξεις ένα 2D παιχνίδι με AI;", "Για ένα μικρό παιχνίδι για κινητά, ένα άτομο με εργαλεία AI ξοδεύει συνήθως περίπου $100–300 σε συνδρομές και API και δουλεύει 2–3 εβδομάδες. Υπολόγισε το δικό σου είδος και μέγεθος με τον υπολογιστή παραπάνω."),
       ("Ποια εργαλεία AI χρειάζομαι για να φτιάξω ένα παιχνίδι;", "Συνήθως τέσσερα: ένα εργαλείο εικόνας για sprites και φόντα (Midjourney, Leonardo, Gemini, PixelLab, Scenario ή ένα API εικόνας), ένα εργαλείο μουσικής (Suno, Stable Audio, AIVA ή δωρεάν μουσική από το Pixabay), ένα εργαλείο για ηχητικά εφέ (ElevenLabs, Stable Audio ή δωρεάν βιβλιοθήκες) και έναν coding agent (Claude Code, Cursor ή Gemini CLI). Το Meshy βοηθά με τα 3D μοντέλα και το Higgsfield με ένα promo βίντεο."),
       ("Πόσα tokens χρειάζονται για να προγραμματίσεις ένα παιχνίδι με το Claude Code;", "Οι agents ξαναδιαβάζουν συνεχώς το project σου, οπότε ένα build 2 εβδομάδων μπορεί να φτάσει μερικές εκατοντάδες εκατομμύρια tokens, κυρίως από την cache. Με το Claude Max πληρώνεις σταθερό ποσό τον μήνα· για το API ο υπολογιστής δείχνει το κόστος του μοντέλου που επέλεξες."),
       ("Μπορώ να χρησιμοποιήσω ελεύθερα τα prompts;", "Ναι. Αντίγραψέ τα ή κατέβασε όλο το πακέτο ως αρχείο Markdown και επικόλλησέ τα στα εργαλεία σου. Τίποτα από όσα συμπληρώνεις δεν ανεβαίνει πουθενά.")],
  defName="Το παιχνίδι μου", defIdea="ένα παιχνίδι {genre} για {plat}",
  g_merge="Merge", g_puzzle="Παζλ", g_racing="Αγώνες", g_idle="Idle", g_platformer="Platformer", g_rpg="RPG", g_novel="Visual novel", g_shooter="Shooter", g_match3="Match-3", g_tower="Tower defense", g_card="Κάρτες / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / διαχείριση", g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Ρυθμός", g_word="Λέξεις / κουίζ", g_farming="Φάρμα / προσομοίωση ζωής", g_escape="Escape room / κρυμμένα αντικείμενα", g_board="Επιτραπέζιο", g_autobattler="Auto battler", g_survival="Επιβίωση / crafting", g_fishing="Ψάρεμα", g_sports="Αθλητικά", g_fighting="Μάχες", g_pet="Φροντίδα κατοικίδιων", g_minigames="Συλλογή minigames", g_metroidvania="Metroidvania", g_strategy="Στρατηγική / 4X", g_gacha="Gacha RPG συλλογής", g_horror="Τρόμου", g_sandbox="Sandbox", g_mmo="MMO / online RPG", gOther="Περισσότερα ▾",
  f_ads="Διαφημίσεις", f_iap="Αγορές εντός εφαρμογής", f_save="Αποθήκευση / φόρτωση", f_rank="Κατάταξη", f_online="Online multiplayer",
  devIntro="Είσαι έμπειρος game developer. Βοήθησέ με να φτιάξω το «{name}», ένα 2D παιχνίδι είδους {genre} για {plat} με {engine}.",
  qPlat="Κυκλοφορεί σε", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web", pls_android="Google Play, εφάπαξ", pls_mobile="Google Play $25 + Apple $99/έτος", pls_pc="Steam Direct, ανά παιχνίδι", pls_web="", l_store="Τέλη store", l_server="Server",
  devIdea="Ιδέα:", devScope="Έκταση: {chars} χαρακτήρες, {bg} φόντα, {items} αντικείμενα, {music} μουσικά κομμάτια, {sfx} ηχητικά εφέ, {langs} γλώσσα/-ες.",
  devFeats="Λειτουργίες:", devRules="Κανόνες: κράτα τον κώδικα απλό και modular· μία λειτουργία σε κάθε βήμα· μετά από κάθε βήμα πες μου πώς να το δοκιμάσω στο κινητό μου· χρησιμοποίησε placeholder σχήματα μέχρι να σου δώσω τα πραγματικά γραφικά.",
  devSteps="Φτιάξ' το με αυτά τα βήματα:", st1="Στήσιμο project, δομή φακέλων, ροή σκηνών (τίτλος → παιχνίδι → αποτέλεσμα)", st2="Βασικός βρόχος gameplay με placeholder γραφικά",
  st3="Σκορ, πρόοδος και καμπύλη δυσκολίας", st4="UI: μενού, HUD, παύση, ρυθμίσεις", st5="Προσθήκη: {feats}", st6="Ενσωμάτωση πραγματικών γραφικών, μουσικής και ηχητικών εφέ", st7="Φινίρισμα, έλεγχος απόδοσης και build για Android",
  devStart="Ξεκίνα με το βήμα 1. Ρώτα με ό,τι χρειάζεσαι πριν γράψεις κώδικα.",
  rImages="Εικόνες", rImagesSub="{chars} χαρακτήρες · {frames} καρέ · {bg} φόντα · {items} αντικείμενα · {ui} UI", rAudio="Μουσική + ήχος", rAudioSub="κομμάτια + εφέ",
  rCode="Γραμμές κώδικα", rCodeSub="εκτίμηση", rTokens="Tokens προγραμματισμού", rTokensSub="≈ {api} μέσω API",
  l_art="Γραφικά", l_music="Μουσική", l_sfx="Ήχος / φωνή", l_code="Κώδικας", l_d3="3D μοντέλα", l_trailer="Trailer",
  p_value="💰 Πιο οικονομικό", p_normal="⚖️ Τυπικό", p_max="🚀 Κορυφαίο", pCustom="Ο δικός σου συνδυασμός", tier_value="οικονομικό", tier_normal="τυπικό", tier_max="premium", pHint="Πάτα έναν συνδυασμό για να αλλάξεις όλα τα εργαλεία μαζί ή άλλαξέ τα ένα-ένα παρακάτω.",
  days="{n} ημέρες", monthsN="{n} μήνες", capWarn="Το όριο χρήσης αυτής της συνδρομής μάλλον δεν φτάνει για καθημερινό προγραμματισμό με agent — υπολόγισε αναμονή ή επιπλέον κόστος.",
  qa='Σύντομη απάντηση: για να φτιάξεις μόνος σου ένα μικρό 2D παιχνίδι για κινητά με εργαλεία AI χρειάζεσαι περίπου 2–3 εβδομάδες και γύρω στα $50–180 σε συνδρομές και API (Οκτώβριος 2026). Το μεγαλύτερο μέρος είναι η συνδρομή για AI προγραμματισμό.', sumTitle='Κόστος και χρόνος ανά είδος και μέγεθος', sumNote='Κάθε κελί: χρόνος ανάπτυξης · κόστος από τον πιο οικονομικό έως τον τυπικό συνδυασμό. Ένα άτομο με AI, USD χωρίς ΦΠΑ, μαζί με τα τέλη store. Ελέγχθηκε στις {date}.',
  cTax="Με ΦΠΑ ({pct}%)", cFx="Ισοτιμία της {date}, κατά προσέγγιση",
  hireRef="Για σύγκριση: η πρόσληψη freelancers για ένα παιχνίδι αυτού του μεγέθους ξεκινά συνήθως από <b>{min}+</b>, και οι προσφορές μπορεί να διαφέρουν δέκα φορές ή και περισσότερο ανάλογα με τη χώρα και την ποιότητα.",
  noTrailer="Ενεργοποίησε το «Promo trailer» για να πάρεις prompts για trailer.",
  copied="Αντιγράφηκε ✓", packTitle="πακέτο prompts",
  related="Δες επίσης", rel=[("/el/agents", "Υπολογιστής κόστους coding agents"), ("/el/image", "Κόστος ανά εικόνα AI"), ("/el/plans", "Συνδρομή ή API;")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (επιδρομές σε βάσεις)", g_plus1="+1 ανά δευτερόλεπτο (απόδραση / ταχύτητα)", g_verbsim="Sim απλής κίνησης (τύπου ξεφλούδισμα πατάτας)",
  g_coophorror="Co-op τρόμου", g_duels="Μονομαχίες 1v1", g_rng="RNG / συλλογή με τύχη", g_coopobby="Co-op obby για 2",
  rbxTitle="🔥 Τι είναι trending στο Roblox τώρα", rbxSub="Τύποι παιχνιδιών που ανεβαίνουν στα charts του Roblox, με ταυτόχρονους παίκτες. Ελέγχθηκε στις {date} στα Roblox Charts.", rbxUse="Χρησιμοποίησέ το →",
  rbxMoney="Στο Roblox δεν υπάρχουν τέλη store και το Roblox τρέχει τους servers δωρεάν. Κερδίζεις Robux από game passes και developer products (κρατάς το 70%) και από τα Premium Payouts, και τα εξαργυρώνεις μέσω DevEx προς $0,0038 ανά Robux (ελάχιστο 30.000 Robux). Παράδειγμα: πωλήσεις 10.000 Robux → 7.000 Robux → περίπου $27.",
  devIntroRbx="Είσαι έμπειρος developer στο Roblox. Βοήθησέ με να φτιάξω το «{name}», ένα experience είδους {genre} στο Roblox, με Roblox Studio και Luau.",
  rbxDev="Ιδιαιτερότητες Roblox: βάλε τη λογική του παιχνιδιού στο ServerScriptService και το UI και την είσοδο του client στο StarterPlayerScripts / StarterGui· να επικοινωνούν μόνο μέσω RemoteEvents και ποτέ μην εμπιστεύεσαι τον client. Αποθήκευε την πρόοδο με το DataStoreService (με επαναλήψεις). Πούλα game passes και developer products μέσω του MarketplaceService. Χρησιμοποίησε το Roblox Assistant στο Studio για μικρές αλλαγές και 3D μοντέλα, και κάνε κάθε βήμα να δοκιμάζεται σε λειτουργία Play.",
  rbxPublish="Φινίρισμα, δοκιμή στο Studio με 2+ παίκτες, ρύθμιση εικονιδίου και thumbnails και δημοσίευση στο Roblox",
)

NAV = "Κόστος παιχνιδιού"
