# -*- coding: utf-8 -*-
"""Finnish (fi) strings for the AI game cost calculator. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same value as gamecost_i18n.CHECKED (copied to avoid importing gamecost modules)

GC = dict(
  title="Paljonko pelin tekeminen AI:lla maksaa?",
  desc="Laske AI-pelisi hinta, aika ja promptit lajityypin, koon ja alustan mukaan.",
  badge="Uusi · ilmainen · ei rekisteröitymistä",
  h1="Pelin kustannuslaskuri AI:lle",
  sub="Vastaa muutamaan kysymykseen 2D-pelistäsi. Saat listan asseteista, hinnan ja ajan sen tekemiseen AI-työkaluilla, tokenmäärän ja promptipaketin, joten pääset alkuun jo tänään.",
  qProject="Pelisi", name="Pelin nimi", namePh="esim. Kissakahvila Merge", idea="Idea yhdellä rivillä", ideaPh="esim. yhdistele kissahuonekaluja ja sisusta kahvila",
  qGenre="Lajityyppi", qScale="Koko",
  sS="Pieni", sSsub="≈ 2 viikkoa yksin", sM="Keskikokoinen", sMsub="≈ 4 viikkoa", sL="Suuri", sLsub="≈ 6 viikkoa", sXL="Erittäin suuri", sXLsub="≈ 3 kuukautta tai enemmän",
  qStyle="Grafiikkatyyli", stPixel="Pikseligrafiikka", stIllust="Kuvitus", stSimple="Yksinkertainen / vektori",
  qDim="Ulkoasu", d2="2D", d3="2.5D / 3D-mallit",
  qChars="Hahmot / viholliset", qAnim="Animaatio", aNone="Ei mitään", aSimple="Yksinkertainen (3 liikettä)", aFull="Täysi (6 liikettä)",
  qMusic="Musiikkikappaleet", qSfx="Ääniefektit", sfFew="Vähän", sfNormal="Normaalisti", sfMany="Paljon",
  qVoice="Ääninäyttelyrepliikit", qFeats="Ominaisuudet", qLangs="Kielet", qEngine="Pelimoottori", qTrailer="Mainostraileri",
  yes="Kyllä", no="Ei",
  qTools="Työkalusi", qImg="Kuvat", qCode="Koodi", qMusicTool="Musiikki", qSfxTool="Ääniefektit", q3dTool="3D-mallit (2.5D / 3D)",
  freeLib="Ilmaiset kirjastot", freeMusic="Pixabay (ilmainen)", qModel="API-malli",
  resTitle="Tätä pelisi tarvitsee", cmpTitle="Hinta ja aika AI:lla",
  promptTitle="Promptipakettisi",
  promptSub="Tehty vastaustesi pohjalta. Assettien promptit ovat englanniksi, koska kuva-, musiikki- ja äänityökalut toimivat parhaiten englanniksi.",
  tDev="Kehityksen aloitus", tArt="Grafiikka", tMusic="Musiikki", tSfx="Ääniefektit", tTrailer="Traileri",
  copy="Kopioi", download="Lataa kaikki (.md)",
  howTitle="Näin arvio lasketaan",
  how=[
    "Koot perustuvat oikeisiin peleihin, jotka yksi ihminen on tehnyt AI-koodausagenttien avulla: pieni mobiilipeli vei noin 2 viikkoa, keskikokoinen noin 4 ja suuri noin 6; erittäin suuri noin 3 kuukautta. Lajityyppi, ominaisuudet, kielet ja 3D muuttavat lukuja.",
    "Kuvat = hahmot × animaatioruudut + taustat + esineet + UI. Oletamme, että pidät noin yhden kolmesta generoinnista, joten generointeja on kolme kertaa kuvien määrä.",
    "Koodin tokenit olettavat, että Claude Coden kaltainen agentti työskentelee noin 70 % päivistä ja lukee noin 20 miljoonaa tokenia päivässä, enimmäkseen välimuistissa olevaa kontekstia. API-hinta käyttää valitsemasi mallin nykyistä listahintaa; tilaukset lasketaan kuukausittain.",
  ],
  srcTitle="Käytetyt työkalujen hinnat", srcNote=f"Tarkistettu {CHECKED}. Hinnat muuttuvat usein – tarkista jokaisen työkalun hintasivu ennen ostamista.",
  faqTitle="Usein kysytyt kysymykset",
  faq=[
    ("Paljonko 2D-pelin tekeminen AI:lla maksaa?",
     "Pieneen mobiilipeliin yksi ihminen AI-työkaluineen käyttää yleensä noin 100–300 USD tilauksiin ja API:in sekä 2–3 viikkoa työtä. Laske oma lajityyppisi ja kokosi yllä olevalla laskurilla."),
    ("Mitä AI-työkaluja tarvitsen pelin tekemiseen?",
     "Yleensä neljä: kuvatyökalun spriteille ja taustoille (Midjourney, Leonardo, Gemini, PixelLab, Scenario tai kuva-API), musiikkityökalun (Suno, Stable Audio, AIVA tai ilmaista musiikkia Pixabaysta), työkalun ääniefekteille (ElevenLabs, Stable Audio tai ilmaiset kirjastot) ja koodausagentin (Claude Code, Cursor tai Gemini CLI). Meshy auttaa, jos haluat 3D-malleja, ja Higgsfield mainosvideoon."),
    ("Montako tokenia pelin koodaaminen Claude Codella vie?",
     "Agentit lukevat projektin yhä uudelleen, joten kahden viikon rakentaminen voi kuluttaa muutamia satoja miljoonia tokeneita, enimmäkseen välimuistista. Claude Maxilla maksat kiinteän kuukausihinnan; API:lla laskuri näyttää valitsemasi mallin hinnan."),
    ("Saanko käyttää prompteja vapaasti?",
     "Kyllä. Kopioi ne tai lataa koko paketti Markdown-tiedostona ja liitä ne työkaluihisi. Mitään kirjoittamaasi ei ladata palvelimelle."),
  ],
  defName="Pelini", defIdea="{genre}-peli alustalle {plat}",
  g_merge="Merge", g_puzzle="Pulma", g_racing="Kilpa-ajo", g_idle="Idle", g_platformer="Tasohyppely", g_rpg="RPG", g_novel="Visuaalinen romaani", g_shooter="Ammuskelu",
  g_match3="Match-3", g_tower="Tower defense", g_card="Kortti / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / johtaminen",
  g_hyper="Hyperkasuaali", g_runner="Juoksu", g_rhythm="Rytmi", g_word="Sana / tietovisa", g_farming="Maatila / elämäsimulaattori",
  g_escape="Pakohuone / piiloesineet", g_board="Lautapeli", g_autobattler="Auto battler", g_survival="Selviytyminen / crafting",
  g_fishing="Kalastus", g_sports="Urheilu", g_fighting="Taistelu", g_pet="Lemmikkien kasvatus", g_minigames="Minipelikokoelma",
  g_metroidvania="Metroidvania", g_strategy="Strategia / 4X", g_gacha="Keräily-gacha-RPG", g_horror="Kauhu",
  g_sandbox="Hiekkalaatikko", g_mmo="MMO / verkkoroolipeli",
  gOther="Lisää ▾",
  f_ads="Mainokset", f_iap="Sovelluksen sisäiset ostot", f_save="Tallennus / lataus", f_rank="Tulostaulukko", f_online="Verkkomoninpeli",
  devIntro='Olet kokenut pelinkehittäjä. Auta minua tekemään "{name}" – 2D-peli, lajityyppi {genre}, alusta {plat}, pelimoottori {engine}.',
  qPlat="Julkaisualusta", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Selain",
  pls_android="Google Play, kertamaksu", pls_mobile="Google Play 25 USD + Apple 99 USD/v", pls_pc="Steam Direct, per peli", pls_web="",
  l_store="Kauppamaksu", l_server="Palvelin",
  devIdea="Idea:",
  devScope="Laajuus: {chars} hahmoa, {bg} taustaa, {items} esinettä, {music} musiikkikappaletta, {sfx} ääniefektiä, {langs} kieltä.",
  devFeats="Ominaisuudet:",
  devRules="Säännöt: pidä koodi yksinkertaisena ja modulaarisena; yksi ominaisuus per vaihe; kerro jokaisen vaiheen jälkeen, miten testaan sen puhelimella; käytä paikkamerkkimuotoja, kunnes annan sinulle oikeat grafiikat.",
  devSteps="Rakenna se näissä vaiheissa:",
  st1="Projektin pystytys, kansiorakenne, näkymien kulku (otsikko → peli → tulos)",
  st2="Peruspelisilmukka paikkamerkkigrafiikalla",
  st3="Pisteet, eteneminen ja vaikeuskäyrä",
  st4="UI: valikot, HUD, tauko, asetukset",
  st5="Lisää: {feats}",
  st6="Kytke mukaan oikeat grafiikat, musiikki ja ääniefektit",
  st7="Viimeistely, suorituskyvyn tarkistus ja Android-käännös",
  devStart="Aloita vaiheesta 1. Kysy minulta kaikki tarvitsemasi ennen kuin kirjoitat koodia.",
  rImages="Kuvat", rImagesSub="{chars} hahmoa · {frames} ruutua · {bg} taustaa · {items} esinettä · {ui} UI",
  rAudio="Musiikki + äänet", rAudioSub="kappaleet + efektit",
  rCode="Koodirivit", rCodeSub="arvio",
  rTokens="Koodin tokenit", rTokensSub="≈ {api} API:n kautta",
  l_art="Grafiikka", l_music="Musiikki", l_sfx="Äänet / puhe", l_code="Koodi", l_d3="3D-mallit", l_trailer="Traileri",
  p_value="💰 Edullisin", p_normal="⚖️ Vakio", p_max="🚀 Huippuluokka", pCustom="Oma yhdistelmäsi",
  tier_value="budjetti", tier_normal="vakio", tier_max="premium",
  pHint="Napsauta yhdistelmää vaihtaaksesi kaikki työkalut kerralla, tai vaihda ne yksitellen alla.",
  days="{n} päivää", monthsN="{n} kk",
  capWarn="Tämän tilauksen käyttöraja ei todennäköisesti riitä päivittäiseen agenttikoodaukseen – varaudu odotteluun tai lisäkäyttöön.",
  qa="Lyhyesti: pienen 2D-mobiilipelin tekeminen yksin AI-työkaluilla vie noin 2–3 viikkoa ja maksaa noin 50–180 USD tilauksina ja API-käyttönä (lokakuu 2026). Suurin osa menee AI-koodaustilaukseen.",
  sumTitle="Hinta ja aika lajityypin ja koon mukaan",
  sumNote="Jokainen solu: kehitysaika · hinta halvimmasta vakioyhdistelmään. Yksi ihminen AI:n kanssa, USD ilman ALV:tä, kauppamaksu mukana. Tarkistettu {date}.",
  cTax="Sis. ALV ({pct} %)",
  cFx="Valuuttakurssi {date}, likimääräinen",
  hireRef="Vertailun vuoksi: freelancereiden palkkaaminen tämän kokoiseen peliin alkaa yleensä noin <b>{min}+</b>, ja tarjoukset voivat erota kymmenkertaisesti tai enemmän maan ja laadun mukaan.",
  noTrailer="Ota ”Mainostraileri” käyttöön saadaksesi trailerin promptit.",
  copied="Kopioitu ✓",
  packTitle="promptipaketti",
  related="Katso myös",
  rel=[("/fi/agents", "Koodausagenttien hintalaskuri"), ("/fi/image", "AI-kuvan hinta"), ("/fi/plans", "Tilaus vai API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (tukikohtien ryöstö)",
  g_plus1="+1 sekunnissa (pako / nopeus)",
  g_verbsim="Yksinkertainen tekemissimu (esim. perunoiden kuorinta)",
  g_coophorror="Co-op-kauhu",
  g_duels="1 vs 1 -kaksintaistelut",
  g_rng="RNG / keräily onnella",
  g_coopobby="Co-op-obby kahdelle",
  rbxTitle="🔥 Nyt trendaa Robloxissa",
  rbxSub="Pelityypit, jotka nousevat Robloxin listoilla, samanaikaisine pelaajineen. Tarkistettu {date} Roblox Chartsista.",
  rbxUse="Käytä →",
  rbxMoney="Robloxissa ei ole kauppamaksua, ja Roblox pyörittää palvelimet ilmaiseksi. Ansaitset Robuxeja game passeilla ja developer productseilla (pidät 70 %) sekä Premium Payoutseilla, ja vaihdat ne DevExin kautta hintaan 0,0038 USD per Robux (vähintään 30 000 Robuxia). Esimerkki: 10 000 Robuxin myynti → 7 000 Robuxia → noin 27 USD.",
  devIntroRbx='Olet kokenut Roblox-kehittäjä. Auta minua tekemään "{name}" – Roblox-peli, lajityyppi {genre}, Roblox Studiossa Luaulla.',
  rbxDev="Roblox-kohtaista: laita pelilogiikka ServerScriptServiceen ja asiakkaan UI ja syöte StarterPlayerScriptsiin / StarterGuihin; anna niiden viestiä vain RemoteEventsien kautta, äläkä koskaan luota asiakkaaseen. Tallenna eteneminen DataStoreServicellä (uudelleenyrityksin). Myy game passeja ja developer productseja MarketplaceServicen kautta. Käytä Studion Roblox Assistantia pieniin muutoksiin ja 3D-malleihin, ja tee jokaisesta vaiheesta testattava Play-tilassa.",
  rbxPublish="Viimeistele, testaa Studiossa 2+ pelaajalla, aseta kuvake ja pikkukuvat ja julkaise Robloxissa",
)

NAV = "Pelin hinta"
