# -*- coding: utf-8 -*-
"""Hungarian (hu) strings for the AI game cost calculator. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same literal as gamecost_i18n.CHECKED (copied to avoid a circular import)

GC = dict(
  title="Mennyibe kerül egy játék AI-jal?", desc="Számold ki AI-játékod költségét, idejét és promptjait műfaj és platform szerint.",
  badge="Új · ingyenes · fiók nélkül", h1="AI-játékköltség-kalkulátor",
  sub="Számold ki, mennyibe kerül és mennyi ideig tart egyedül elkészíteni egy 2D-s vagy 3D-s játékot AI-jal. A kalkulátort egy valódi, megjelent játékon ellenőriztük, és az assetek listáját meg egy kezdő promptcsomagot is megkapod.",
  qProject="A játékod", name="A játék neve", namePh="pl. Cat Café Merge", idea="Az ötlet egy mondatban", ideaPh="pl. macskabútorok egyesítése és egy kávézó berendezése",
  qGenre="Műfaj", qScale="Méret", sS="Kicsi", sSsub="≈ 2 hét egyedül", sM="Közepes", sMsub="≈ 4 hét", sL="Nagy", sLsub="≈ 6 hét", sXL="Nagyon nagy", sXLsub="≈ 3 hónap vagy több",
  qStyle="Grafikai stílus", stPixel="Pixel art", stIllust="Illusztráció", stSimple="Egyszerű / vektoros",
  qDim="Megjelenítés", d2="2D", d3="2.5D / 3D modellek",
  qChars="Karakterek / ellenségek", qAnim="Animáció", aNone="Nincs", aSimple="Egyszerű (3 mozdulat)", aFull="Teljes (6 mozdulat)",
  qMusic="Zeneszámok", qSfx="Hangeffektek", sfFew="Kevés", sfNormal="Normál", sfMany="Sok", qVoice="Szinkronsorok",
  qFeats="Funkciók", qLangs="Nyelvek", qEngine="Motor", qTrailer="Promó trailer", yes="Igen", no="Nem",
  qTools="Az eszközeid", qImg="Képek", qCode="Programozás", qMusicTool="Zene", qSfxTool="Hangeffektek", q3dTool="3D modellek (2.5D / 3D esetén)", freeLib="Ingyenes könyvtárak", freeMusic="Pixabay (ingyenes)", qModel="API-modell",
  resTitle="Mire van szüksége a játékodnak", cmpTitle="Költség és idő AI-jal",
  promptTitle="A promptcsomagod", promptSub="A válaszaid alapján készült. Az asset-promptok angolul vannak, mert a kép-, zene- és hangeszközök angolul működnek a legjobban.",
  tDev="Fejlesztés indítása", tArt="Grafika", tMusic="Zene", tSfx="Hangeffektek", tTrailer="Trailer", copy="Másolás", download="Összes letöltése (.md)",
  howTitle="Így becsülünk",
  how=["A méretek valódi játékokon alapulnak, amelyeket egyetlen ember készített AI kódoló agentekkel: egy kis mobiljáték nagyjából 2 hét volt, egy közepes kb. 4, egy nagy kb. 6; egy nagyon nagy kb. 3 hónap. A műfaj, a funkciók, a nyelvek és a 3D módosítják ezeket a számokat.",
       "Képek = karakterek × animációs képkockák + hátterek + tárgyak + UI. Feltételezzük, hogy nagyjából minden 3. generálást tartasz meg, így háromszor annyi generálás van, mint kép.",
       "A kódolási tokenek azzal számolnak, hogy egy agent, például a Claude Code, a napok kb. 70%-ában dolgozik, és naponta mintegy 20 millió tokent olvas, többnyire cache-elt kontextust. Az API-költség a kiválasztott modell aktuális listaárát használja; az előfizetéseket havonta számoljuk."],
  srcTitle="Felhasznált eszközárak", srcNote=f"Ellenőrizve: {CHECKED}. Az árak gyakran változnak – vásárlás előtt nézd meg minden eszköz árazási oldalát.",
  faqTitle="Gyakori kérdések",
  faq=[("Mennyibe kerül egy 2D-s játék elkészítése AI-jal?", "Egy kis mobiljátéknál egy ember AI-eszközökkel általában kb. $100–300-t költ előfizetésekre és API-ra, és 2–3 hétig dolgozik rajta. Számold ki a saját műfajodat és méretedet a fenti kalkulátorral."),
       ("Milyen AI-eszközök kellenek egy játék elkészítéséhez?", "Általában négy: egy képeszköz a sprite-okhoz és háttérképekhez (Midjourney, Leonardo, Gemini, PixelLab, Scenario vagy egy kép-API), egy zeneeszköz (Suno, Stable Audio, AIVA vagy ingyenes zene a Pixabayről), egy hangeffekt-eszköz (ElevenLabs, Stable Audio vagy ingyenes könyvtárak) és egy kódoló agent (Claude Code, Cursor vagy Gemini CLI). A Meshy a 3D modellekben, a Higgsfield egy promóvideóban segít."),
       ("Hány tokenbe kerül egy játék leprogramozása a Claude Code-dal?", "Az agentek folyamatosan újraolvassák a projektedet, így egy 2 hetes build akár néhány százmillió tokent is elérhet, többnyire cache-ből. A Claude Maxszal havi fix összeget fizetsz; API esetén a kalkulátor a kiválasztott modell költségét mutatja."),
       ("Szabadon használhatom a promptokat?", "Igen. Másold ki őket, vagy töltsd le az egész csomagot Markdown-fájlként, és illeszd be az eszközeidbe. Semmi, amit beírsz, nem kerül feltöltésre.")],
  defName="Az én játékom", defIdea="egy {genre} játék {plat} platformra",
  g_merge="Merge", g_puzzle="Puzzle", g_racing="Verseny", g_idle="Idle", g_platformer="Platformer", g_rpg="RPG", g_novel="Visual novel", g_shooter="Lövöldözős", g_match3="Match-3", g_tower="Tower defense", g_card="Kártya / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / menedzser", g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Ritmus", g_word="Szójáték / kvíz", g_farming="Farm / életszimuláció", g_escape="Szabadulószoba / rejtett tárgyak", g_board="Társasjáték", g_autobattler="Auto battler", g_survival="Túlélő / crafting", g_fishing="Horgászat", g_sports="Sport", g_fighting="Verekedős", g_pet="Kisállatgondozás", g_minigames="Minijáték-gyűjtemény", g_metroidvania="Metroidvania", g_strategy="Stratégia / 4X", g_gacha="Gyűjtögetős gacha RPG", g_horror="Horror", g_sandbox="Sandbox", g_mmo="MMO / online RPG", gOther="Továbbiak ▾",
  f_ads="Hirdetések", f_iap="Alkalmazáson belüli vásárlás", f_save="Mentés / betöltés", f_rank="Ranglista", f_online="Online multiplayer",
  devIntro="Tapasztalt játékfejlesztő vagy. Segíts megépíteni a(z) „{name}” nevű {dim}-s {genre} játékot {plat} platformra, {engine} használatával.",
  qPlat="Megjelenik itt", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web", pls_android="Google Play, egyszeri", pls_mobile="Google Play $25 + Apple $99/év", pls_pc="Steam Direct, játékonként", pls_web="", feeIncl="Áruházi regisztrációs díj beszámítása (ha még nem fizetted ki)", l_store="Store-díjak", l_server="Szerver",
  devIdea="Ötlet:", devScope="Terjedelem: {chars} karakter, {bg} háttér, {items} tárgy, {music} zeneszám, {sfx} hangeffekt, {langs} nyelv.",
  devFeats="Funkciók:", devRules="Szabályok: legyen a kód egyszerű és moduláris; lépésenként egy funkció; minden lépés után mondd el, hogyan tesztelem a telefonomon; használj helyettesítő formákat, amíg oda nem adom a valódi grafikát.",
  devSteps="Ezekben a lépésekben építsd fel:", st1="Projekt beállítása, mappaszerkezet, jelenetfolyam (cím → játék → eredmény)", st2="Alap játékmenet-ciklus helyettesítő grafikával",
  st3="Pontszám, előrehaladás és nehézségi görbe", st4="UI: menük, HUD, szünet, beállítások", st5="Hozzáadás: {feats}", st6="Valódi grafika, zene és hangeffektek beépítése", st7="Csiszolás, teljesítményellenőrzés és Android-build",
  devStart="Kezdd az 1. lépéssel. Kérdezz meg mindenről, amire szükséged van, mielőtt kódot írsz.",
  rImages="Képek", rImagesSub="{chars} karakter · {frames} képkocka · {bg} háttér · {items} tárgy · {ui} UI", rAudio="Zene + hang", rAudioSub="számok + effektek",
  rCode="Kódsorok", rCodeSub="becsült", rTokens="Kódolási tokenek", rTokensSub="≈ {api} API-n keresztül",
  l_art="Grafika", l_music="Zene", l_sfx="Hang / szinkron", l_code="Kód", l_d3="3D modellek", l_trailer="Trailer",
  p_value="💰 Legolcsóbb", p_normal="⚖️ Átlagos", p_max="🚀 Csúcskategória", pCustom="A te kombinációd", tier_value="olcsó", tier_normal="átlagos", tier_max="prémium", pHint="Kattints egy kombinációra, hogy egyszerre válts minden eszközt, vagy lent egyenként módosítsd őket.",
  days="{n} nap", monthsN="{n} hónap", capWarn="Ennek az előfizetésnek a használati limitje valószínűleg nem elég a napi agentes kódoláshoz – számolj várakozással vagy plusz költséggel.",
  qa='Röviden: egy kis 2D-s mobiljáték egyedüli elkészítése AI-eszközökkel kb. 2–3 hét, és nagyjából $50–180-ba kerül előfizetésekre és API-ra (2026. október). A legnagyobb tétel az AI-kódoló előfizetés.', sumTitle='Költség és idő műfaj és méret szerint', sumNote='Minden cella: fejlesztési idő · költség a legolcsóbbtól az átlagos kombinációig. Egy ember AI-jal, USD ÁFA nélkül, store-díjakkal együtt. Ellenőrizve: {date}.',
  cTax="ÁFA-val ({pct}%)", cFx="{date}-i árfolyam, hozzávetőleges",
  hireRef="Összehasonlításképp: szabadúszók felvétele egy ekkora játékhoz általában <b>{min}+</b> összegtől indul, és az ajánlatok országtól és minőségtől függően akár tízszeresen vagy még jobban is eltérhetnek.",
  noTrailer="Kapcsold be a „Promó trailer” opciót, hogy trailer-promptokat kapj.",
  copied="Kimásolva ✓", packTitle="promptcsomag",
  related="Lásd még", rel=[("/hu/agents", "Coding agent költségkalkulátor"), ("/hu/image", "Költség AI-képenként"), ("/hu/plans", "Előfizetés vagy API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (bázisok kifosztása)", g_plus1="+1 másodpercenként (szökés / sebesség)", g_verbsim="Egyszerű mozdulatos szimulátor (krumplihámozós típus)",
  g_coophorror="Co-op horror", g_duels="1v1 párbajok", g_rng="RNG / szerencsealapú gyűjtögetés", g_coopobby="Kétszemélyes co-op obby",
  rbxTitle="🔥 Most felkapott a Robloxon", rbxSub="A Roblox toplistáin emelkedő játéktípusok, egyidejű játékosszámmal. Ellenőrizve: {date}, Roblox Charts.", rbxUse="Ezt használom →",
  rbxMoney="A Robloxon nincs store-díj, és a szervereket a Roblox ingyen futtatja. Robuxot game passokkal és developer productokkal (a 70%-a a tiéd) és a Premium Payoutsból keresel, majd a DevEx-en keresztül váltod be Robuxonként $0,0038-ért (minimum 30 000 Robux). Példa: 10 000 Robux eladás → 7000 Robux → kb. $27.",
  devIntroRbx="Tapasztalt Roblox-fejlesztő vagy. Segíts megépíteni a(z) „{name}” nevű {genre} experience-et a Robloxon, Roblox Studióban, Luau nyelven.",
  rbxDev="Roblox-specifikus tudnivalók: a játéklogikát tedd a ServerScriptService-be, a kliens UI-ját és bemenetkezelését a StarterPlayerScripts / StarterGui-ba; a kettő csak RemoteEventeken keresztül kommunikáljon, és soha ne bízz a kliensben. Az előrehaladást DataStoreService-szel mentsd (újrapróbálkozással). A game passokat és developer productokat a MarketplaceService-en keresztül add el. Kisebb módosításokhoz és 3D modellekhez használd a Studio Roblox Assistantját, és minden lépés legyen tesztelhető Play módban.",
  rbxPublish="Csiszolás, tesztelés Studióban 2+ játékossal, ikon és thumbnailok beállítása, majd közzététel a Robloxon",
)

NAV = "Játékköltség"
