# -*- coding: utf-8 -*-
"""Italian (it) strings for the AI game cost calculator + Roblox block. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same value as gamecost_i18n.CHECKED (defined there, not imported to avoid cycles)

GC = dict(
  title="Quanto costa creare un gioco con l'IA?", desc="Calcola costi, tempi e prompt del tuo gioco IA per genere, scala e piattaforma.",
  badge="Nuovo · gratis · senza account", h1="Calcolatore costi giochi con IA",
  sub="Calcola costi e tempi per creare da solo un gioco 2D o 3D con l'IA. Il calcolatore è stato verificato su un vero gioco pubblicato e ti dà anche la lista degli asset e un pacchetto di prompt per iniziare.",
  qProject="Il tuo gioco", name="Nome del gioco", namePh="es. Gatti Café Merge", idea="L'idea in una frase", ideaPh="es. unire mobili per gatti e arredare un caffè",
  qGenre="Genere", qScale="Dimensione", sS="Piccolo", sSsub="≈ 2 settimane da solo", sM="Medio", sMsub="≈ 4 settimane", sL="Grande", sLsub="≈ 6 settimane", sXL="Molto grande", sXLsub="≈ 3 mesi o più",
  qStyle="Stile grafico", stPixel="Pixel art", stIllust="Illustrazione", stSimple="Semplice / vettoriale",
  qDim="Visuale", d2="2D", d3="2.5D / modelli 3D",
  qChars="Personaggi / nemici", qAnim="Animazione", aNone="Nessuna", aSimple="Semplice (3 movimenti)", aFull="Completa (6 movimenti)",
  qMusic="Brani musicali", qSfx="Effetti sonori", sfFew="Pochi", sfNormal="Normali", sfMany="Molti", qVoice="Battute doppiate",
  qFeats="Funzioni", qLangs="Lingue", qEngine="Engine", qTrailer="Trailer promozionale", yes="Sì", no="No",
  qTools="I tuoi strumenti", qImg="Immagini", qCode="Programmazione", qMusicTool="Musica", qSfxTool="Effetti sonori", q3dTool="Modelli 3D (con 2.5D / 3D)", freeLib="Librerie gratuite", freeMusic="Pixabay (gratis)", qModel="Modello API",
  resTitle="Cosa serve al tuo gioco", cmpTitle="Costi e tempi con l'IA",
  promptTitle="Il tuo pacchetto di prompt", promptSub="Creato dalle tue risposte. I prompt per gli asset sono in inglese, perché gli strumenti per immagini, musica e suoni funzionano meglio in inglese.",
  tDev="Avvio sviluppo", tArt="Grafica", tMusic="Musica", tSfx="Effetti sonori", tTrailer="Trailer", copy="Copia", download="Scarica tutto (.md)",
  howTitle="Come lo stimiamo",
  how=["Le dimensioni si basano su giochi reali creati da una sola persona con agenti di codice IA: un piccolo gioco mobile ha richiesto circa 2 settimane, uno medio circa 4 e uno grande circa 6; uno molto grande circa 3 mesi. Genere, funzioni, lingue e 3D cambiano questi numeri.",
       "Immagini = personaggi × frame di animazione + sfondi + oggetti + UI. Supponiamo che tu tenga circa 1 generazione su 3, quindi le generazioni sono il triplo delle immagini.",
       "I token di codice presuppongono un agente come Claude Code al lavoro circa il 70% dei giorni, che legge circa 20 milioni di token al giorno, per lo più contesto in cache. I costi API usano il prezzo di listino attuale del modello scelto; gli abbonamenti si contano a mese."],
  srcTitle="Prezzi degli strumenti usati", srcNote=f"Verificato il {CHECKED}. I prezzi cambiano spesso: controlla la pagina dei prezzi di ogni strumento prima di acquistare.",
  faqTitle="Domande frequenti",
  faq=[("Quanto costa creare un gioco 2D con l'IA?", "Per un piccolo gioco mobile, una persona con strumenti IA spende di solito circa 100–300 $ tra abbonamenti e API e ci mette 2–3 settimane. Calcola il tuo genere e la tua dimensione con il calcolatore qui sopra."),
       ("Quali strumenti IA servono per creare un gioco?", "Di solito quattro: uno strumento per immagini per sprite e sfondi (Midjourney, Leonardo, Gemini, PixelLab, Scenario o un'API di immagini), uno per la musica (Suno, Stable Audio, AIVA o musica gratuita di Pixabay), uno per gli effetti sonori (ElevenLabs, Stable Audio o librerie gratuite) e un agente di codice (Claude Code, Cursor o Gemini CLI). Meshy aiuta con i modelli 3D, Higgsfield con un video promozionale."),
       ("Quanti token servono per programmare un gioco con Claude Code?", "Gli agenti rileggono continuamente il progetto, quindi uno sviluppo di 2 settimane può arrivare a qualche centinaio di milioni di token, per lo più dalla cache. Con Claude Max paghi una cifra fissa al mese; con l'API il calcolatore mostra il costo del modello scelto."),
       ("Posso usare liberamente i prompt?", "Sì. Copiali o scarica l'intero pacchetto come file Markdown e incollali nei tuoi strumenti. Niente di ciò che inserisci viene caricato online.")],
  defName="Il mio gioco", defIdea="un gioco {genre} per {plat}",
  g_merge="Merge", g_puzzle="Puzzle", g_racing="Corse", g_idle="Idle", g_platformer="Platform", g_rpg="RPG", g_novel="Visual novel", g_shooter="Sparatutto", g_match3="Match-3", g_tower="Tower defense", g_card="Carte / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / gestionale", g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Ritmo", g_word="Parole / quiz", g_farming="Fattoria / simulazione di vita", g_escape="Escape room / oggetti nascosti", g_board="Gioco da tavolo", g_autobattler="Auto battler", g_survival="Sopravvivenza / crafting", g_fishing="Pesca", g_sports="Sport", g_fighting="Picchiaduro", g_pet="Cura degli animali", g_minigames="Raccolta di minigiochi", g_metroidvania="Metroidvania", g_strategy="Strategia / 4X", g_gacha="RPG gacha collezionabile", g_horror="Horror", g_sandbox="Sandbox", g_mmo="MMO / RPG online", gOther="Altro ▾",
  f_ads="Pubblicità", f_iap="Acquisti in-app", f_save="Salvataggio / caricamento", f_rank="Classifica", f_online="Multigiocatore online",
  devIntro="Sei uno sviluppatore di videogiochi esperto. Aiutami a creare \"{name}\", un gioco {dim} di genere {genre} per {plat} con {engine}.",
  qPlat="Uscita su", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web", pls_android="Google Play, una tantum", pls_mobile="Google Play $25 + Apple $99/anno", pls_pc="Steam Direct, per gioco", pls_web="", feeIncl="Includi la quota di registrazione allo store (se non l'hai ancora pagata)", l_store="Costi store", l_server="Server",
  devIdea="Idea:", devScope="Contenuti: {chars} personaggi, {bg} sfondi, {items} oggetti, {music} brani musicali, {sfx} effetti sonori, {langs} lingua/e.",
  devFeats="Funzioni:", devRules="Regole: mantieni il codice semplice e modulare; una funzione per passo; dopo ogni passo dimmi come provarlo sul mio telefono; usa forme segnaposto finché non ti do la grafica vera.",
  devSteps="Costruiscilo in questi passi:", st1="Setup del progetto, struttura delle cartelle, flusso delle scene (titolo → gioco → risultato)", st2="Loop di gameplay principale con grafica segnaposto",
  st3="Punteggio, progressione e curva di difficoltà", st4="UI: menu, HUD, pausa, impostazioni", st5="Aggiungi: {feats}", st6="Inserisci grafica, musica ed effetti sonori definitivi", st7="Rifinitura, controllo prestazioni e build Android",
  devStart="Inizia dal passo 1. Chiedimi tutto ciò che ti serve prima di scrivere codice.",
  rImages="Immagini", rImagesSub="{chars} personaggi · {frames} frame · {bg} sfondi · {items} oggetti · {ui} UI", rAudio="Musica + suoni", rAudioSub="brani + effetti",
  rCode="Righe di codice", rCodeSub="stima", rTokens="Token di codice", rTokensSub="≈ {api} via API",
  l_art="Grafica", l_music="Musica", l_sfx="Suoni / voce", l_code="Codice", l_d3="Modelli 3D", l_trailer="Trailer",
  p_value="💰 Più economico", p_normal="⚖️ Standard", p_max="🚀 Top di gamma", pCustom="La tua combinazione", tier_value="economico", tier_normal="standard", tier_max="premium", pHint="Clicca su una combinazione per cambiare tutti gli strumenti in una volta, oppure modificali uno per uno qui sotto.",
  days="{n} giorni", monthsN="{n} mesi", capWarn="Il limite di utilizzo di questo abbonamento probabilmente non basta per programmare ogni giorno con un agente: mettiti in conto attese o costi extra.",
  qa="In breve: creare da solo un piccolo gioco mobile 2D con strumenti IA richiede circa 2–3 settimane e costa circa 50–180 $ tra abbonamenti e API (ottobre 2026). La parte maggiore è l'abbonamento per il coding con IA.", sumTitle="Costi e tempi per genere e dimensione", sumNote="Ogni cella: tempo di sviluppo · costo dalla combinazione più economica a quella standard. Una persona con IA, USD IVA esclusa, costi store inclusi. Verificato il {date}.",
  cTax="IVA inclusa ({pct}%)", cFx="Tasso di cambio del {date}, arrotondato",
  hireRef="Per confronto: assumere freelance per un gioco di queste dimensioni parte di solito da <b>{min}+</b>, e i preventivi possono variare di dieci volte o più a seconda del paese e della qualità.",
  noTrailer="Attiva «Trailer promozionale» per ottenere i prompt del trailer.",
  copied="Copiato ✓", packTitle="pacchetto di prompt",
  related="Vedi anche", rel=[("/it/agents", "Costo degli agenti di codice"), ("/it/image", "Costo per immagine IA"), ("/it/plans", "Abbonamento o API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (assalto alle basi)", g_plus1="+1 al secondo (fuga / velocità)", g_verbsim="Simulatore di azione semplice (tipo sbucciare patate)",
  g_coophorror="Horror cooperativo", g_duels="Duelli 1 contro 1", g_rng="RNG / collezionare con la fortuna", g_coopobby="Obby cooperativo per 2",
  rbxTitle="🔥 Di tendenza su Roblox adesso", rbxSub="Tipi di gioco in crescita nelle classifiche di Roblox, con i giocatori simultanei. Verificato il {date} su Roblox Charts.", rbxUse="Usa questo →",
  rbxMoney="Su Roblox non ci sono costi di store e Roblox gestisce i server gratis. Guadagni Robux con game pass e developer product (tieni il 70%) e con i Premium Payouts, poi li incassi tramite DevEx a $0,0038 per Robux (minimo 30.000 Robux). Esempio: 10.000 Robux di vendite → 7.000 Robux → circa $27.",
  devIntroRbx="Sei uno sviluppatore Roblox esperto. Aiutami a creare \"{name}\", un'esperienza di genere {genre} su Roblox, in Roblox Studio con Luau.",
  rbxDev="Specifiche Roblox: metti la logica di gioco in ServerScriptService e la UI e l'input del client in StarterPlayerScripts / StarterGui; falli comunicare solo tramite RemoteEvent e non fidarti mai del client. Salva i progressi con DataStoreService (con nuovi tentativi). Vendi game pass e developer product tramite MarketplaceService. Usa Roblox Assistant in Studio per piccole modifiche e modelli 3D, e rendi ogni passo testabile in modalità Play.",
  rbxPublish="Rifinisci, prova in Studio con 2+ giocatori, imposta icona e miniature e pubblica su Roblox",
)

NAV = "Costo gioco"
