# -*- coding: utf-8 -*-
"""Norwegian Bokmål (no) strings for the AI game cost calculator. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same value as gamecost_i18n.CHECKED (copied to avoid importing gamecost modules)

GC = dict(
  title="Hva koster det å lage et spill med AI?",
  desc="Regn ut pris, tid og prompter for AI-spillet ditt etter sjanger og størrelse.",
  badge="Nytt · gratis · ingen registrering",
  h1="Kalkulator for spillkostnad med AI",
  sub="Svar på noen spørsmål om 2D-spillet ditt. Du får listen over assets, kostnaden og tiden for å bygge det med AI-verktøy, antall tokens og en promptpakke, så du kan sette i gang i dag.",
  qProject="Spillet ditt", name="Spillets navn", namePh="f.eks. Kattekafé Merge", idea="Idéen på én linje", ideaPh="f.eks. slå sammen kattemøbler og innred en kafé",
  qGenre="Sjanger", qScale="Størrelse",
  sS="Lite", sSsub="≈ 2 uker alene", sM="Middels", sMsub="≈ 4 uker", sL="Stort", sLsub="≈ 6 uker", sXL="Svært stort", sXLsub="≈ 3 måneder eller mer",
  qStyle="Grafisk stil", stPixel="Pikselgrafikk", stIllust="Illustrasjon", stSimple="Enkel / vektor",
  qDim="Utseende", d2="2D", d3="2.5D / 3D-modeller",
  qChars="Figurer / fiender", qAnim="Animasjon", aNone="Ingen", aSimple="Enkel (3 bevegelser)", aFull="Full (6 bevegelser)",
  qMusic="Musikkspor", qSfx="Lydeffekter", sfFew="Få", sfNormal="Normalt", sfMany="Mange",
  qVoice="Stemmereplikker", qFeats="Funksjoner", qLangs="Språk", qEngine="Motor", qTrailer="Reklametrailer",
  yes="Ja", no="Nei",
  qTools="Verktøyene dine", qImg="Bilder", qCode="Kode", qMusicTool="Musikk", qSfxTool="Lydeffekter", q3dTool="3D-modeller (ved 2.5D / 3D)",
  freeLib="Gratis biblioteker", freeMusic="Pixabay (gratis)", qModel="API-modell",
  resTitle="Dette trenger spillet ditt", cmpTitle="Kostnad og tid med AI",
  promptTitle="Promptpakken din",
  promptSub="Laget ut fra svarene dine. Promptene for assets er på engelsk, fordi bilde-, musikk- og lydverktøy fungerer best på engelsk.",
  tDev="Utviklingsstart", tArt="Grafikk", tMusic="Musikk", tSfx="Lydeffekter", tTrailer="Trailer",
  copy="Kopier", download="Last ned alt (.md)",
  howTitle="Slik regnes anslaget ut",
  how=[
    "Størrelsene bygger på ekte spill laget av én person med AI-kodeagenter: et lite mobilspill tok rundt 2 uker, et middels rundt 4 og et stort rundt 6; et svært stort rundt 3 måneder. Sjanger, funksjoner, språk og 3D endrer tallene.",
    "Bilder = figurer × animasjonsrammer + bakgrunner + gjenstander + UI. Vi antar at du beholder omtrent 1 av 3 genereringer, så det blir tre ganger så mange genereringer som bilder.",
    "Kodetokens forutsetter at en agent som Claude Code jobber omtrent 70 % av dagene og leser rundt 20 millioner tokens om dagen, mest bufret kontekst. API-kostnaden bruker dagens listepris for modellen du velger; abonnementer regnes per måned.",
  ],
  srcTitle="Verktøypriser som brukes", srcNote=f"Sjekket {CHECKED}. Prisene endrer seg ofte – sjekk prissiden til hvert verktøy før du kjøper.",
  faqTitle="Vanlige spørsmål",
  faq=[
    ("Hva koster det å lage et 2D-spill med AI?",
     "For et lite mobilspill bruker én person med AI-verktøy vanligvis rundt 100–300 USD på abonnementer og API og 2–3 ukers arbeid. Regn på din egen sjanger og størrelse i kalkulatoren over."),
    ("Hvilke AI-verktøy trenger jeg for å lage et spill?",
     "Vanligvis fire: et bildeverktøy for sprites og bakgrunner (Midjourney, Leonardo, Gemini, PixelLab, Scenario eller et bilde-API), et musikkverktøy (Suno, Stable Audio, AIVA eller gratis musikk fra Pixabay), et verktøy for lydeffekter (ElevenLabs, Stable Audio eller gratis biblioteker) og en kodeagent (Claude Code, Cursor eller Gemini CLI). Meshy hjelper hvis du vil ha 3D-modeller, og Higgsfield for en reklamevideo."),
    ("Hvor mange tokens går med til å kode et spill med Claude Code?",
     "Agenter leser prosjektet om og om igjen, så to ukers bygging kan komme opp i noen hundre millioner tokens, mest fra bufferen. Med Claude Max betaler du en fast månedspris; med API-et viser kalkulatoren kostnaden for modellen du velger."),
    ("Kan jeg bruke promptene fritt?",
     "Ja. Kopier dem eller last ned hele pakken som en Markdown-fil, og lim dem inn i verktøyene dine. Ingenting du skriver, blir lastet opp."),
  ],
  defName="Spillet mitt", defIdea="et {genre}-spill for {plat}",
  g_merge="Merge", g_puzzle="Puslespill", g_racing="Racing", g_idle="Idle", g_platformer="Plattformspill", g_rpg="RPG", g_novel="Visual novel", g_shooter="Skytespill",
  g_match3="Match-3", g_tower="Tower defense", g_card="Kort / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / management",
  g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Rytme", g_word="Ord / quiz", g_farming="Gårdsliv / livssimulator",
  g_escape="Escape room / skjulte gjenstander", g_board="Brettspill", g_autobattler="Auto battler", g_survival="Overlevelse / crafting",
  g_fishing="Fiske", g_sports="Sport", g_fighting="Fighting", g_pet="Kjæledyroppdrett", g_minigames="Samling minispill",
  g_metroidvania="Metroidvania", g_strategy="Strategi / 4X", g_gacha="Gacha-RPG med samling", g_horror="Skrekk",
  g_sandbox="Sandkasse", g_mmo="MMO / online-RPG",
  gOther="Flere ▾",
  f_ads="Annonser", f_iap="Kjøp i appen", f_save="Lagre / laste inn", f_rank="Toppliste", f_online="Online flerspiller",
  devIntro='Du er en erfaren spillutvikler. Hjelp meg å bygge "{name}", et 2D-{genre}-spill for {plat} i {engine}.',
  qPlat="Lanseres på", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Nett",
  pls_android="Google Play, én gang", pls_mobile="Google Play 25 USD + Apple 99 USD/år", pls_pc="Steam Direct, per spill", pls_web="",
  l_store="Butikkavgift", l_server="Server",
  devIdea="Idé:",
  devScope="Omfang: {chars} figurer, {bg} bakgrunner, {items} gjenstander, {music} musikkspor, {sfx} lydeffekter, {langs} språk.",
  devFeats="Funksjoner:",
  devRules="Regler: hold koden enkel og modulær; én funksjon per trinn; fortell meg etter hvert trinn hvordan jeg tester det på mobilen; bruk plassholderformer til jeg gir deg den ekte grafikken.",
  devSteps="Bygg det i disse trinnene:",
  st1="Prosjektoppsett, mappestruktur, sceneflyt (tittel → spill → resultat)",
  st2="Grunnleggende spilløkke med plassholdergrafikk",
  st3="Poeng, progresjon og vanskelighetskurve",
  st4="UI: menyer, HUD, pause, innstillinger",
  st5="Legg til: {feats}",
  st6="Koble inn ekte grafikk, musikk og lydeffekter",
  st7="Finpuss, ytelsessjekk og bygg for Android",
  devStart="Start med trinn 1. Spør meg om alt du trenger før du skriver kode.",
  rImages="Bilder", rImagesSub="{chars} figurer · {frames} rammer · {bg} bakgrunner · {items} gjenstander · {ui} UI",
  rAudio="Musikk + lyd", rAudioSub="spor + effekter",
  rCode="Kodelinjer", rCodeSub="anslått",
  rTokens="Kodetokens", rTokensSub="≈ {api} via API",
  l_art="Grafikk", l_music="Musikk", l_sfx="Lyd / stemme", l_code="Kode", l_d3="3D-modeller", l_trailer="Trailer",
  p_value="💰 Mest for pengene", p_normal="⚖️ Standard", p_max="🚀 Toppklasse", pCustom="Din kombinasjon",
  tier_value="budsjett", tier_normal="standard", tier_max="premium",
  pHint="Klikk på en kombinasjon for å bytte alle verktøyene samtidig, eller bytt dem ett og ett nedenfor.",
  days="{n} dager", monthsN="{n} mnd.",
  capWarn="Bruksgrensen i dette abonnementet holder trolig ikke til agentkoding hver dag – regn med ventetid eller ekstra bruk.",
  qa="Kort svar: å lage et lite 2D-mobilspill alene med AI-verktøy tar rundt 2–3 uker og koster omtrent 50–180 USD i abonnementer og API (oktober 2026). Mesteparten går til AI-kodeabonnementet.",
  sumTitle="Kostnad og tid per sjanger og størrelse",
  sumNote="Hver celle: utviklingstid · kostnad fra den billigste til standardkombinasjonen. Én person med AI, USD eks. mva., butikkavgift inkludert. Sjekket {date}.",
  cTax="Inkl. mva. ({pct} %)",
  cFx="Valutakurs {date}, omtrentlig",
  hireRef="Til sammenligning: å leie inn frilansere til et spill av denne størrelsen starter vanligvis på <b>{min}+</b>, og tilbudene kan variere ti ganger eller mer avhengig av land og kvalitet.",
  noTrailer="Slå på «Reklametrailer» for å få trailerprompter.",
  copied="Kopiert ✓",
  packTitle="promptpakke",
  related="Se også",
  rel=[("/no/agents", "Priskalkulator for kodeagenter"), ("/no/image", "Pris per AI-bilde"), ("/no/plans", "Abonnement eller API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (plyndre baser)",
  g_plus1="+1 per sekund (flukt / fart)",
  g_verbsim="Enkel handlings-sim (f.eks. skrelle poteter)",
  g_coophorror="Co-op-skrekk",
  g_duels="1-mot-1-dueller",
  g_rng="RNG / samle med flaks",
  g_coopobby="Co-op-obby for 2",
  rbxTitle="🔥 Trender på Roblox akkurat nå",
  rbxSub="Spilltyper som klatrer på Roblox-listene, med samtidige spillere. Sjekket {date} på Roblox Charts.",
  rbxUse="Bruk →",
  rbxMoney="På Roblox er det ingen butikkavgift, og Roblox kjører serverne gratis. Du tjener Robux på game passes og developer products (du beholder 70 %) og på Premium Payouts, og veksler dem via DevEx til 0,0038 USD per Robux (minst 30 000 Robux). Eksempel: 10 000 Robux i salg → 7 000 Robux → rundt 27 USD.",
  devIntroRbx='Du er en erfaren Roblox-utvikler. Hjelp meg å bygge "{name}", et {genre}-spill på Roblox, i Roblox Studio med Luau.',
  rbxDev="Roblox-spesifikt: legg spillogikken i ServerScriptService og klientens UI og input i StarterPlayerScripts / StarterGui; la dem bare snakke sammen via RemoteEvents, og stol aldri på klienten. Lagre fremgang med DataStoreService (med nye forsøk). Selg game passes og developer products via MarketplaceService. Bruk Roblox Assistant i Studio til små endringer og 3D-modeller, og gjør hvert trinn testbart i Play-modus.",
  rbxPublish="Finpuss, test med 2+ spillere i Studio, legg inn ikon og miniatyrbilder, og publiser på Roblox",
)

NAV = "Spillkostnad"
