# -*- coding: utf-8 -*-
"""Romanian (ro) strings for the AI game cost calculator. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same literal as gamecost_i18n.CHECKED (copied to avoid a circular import)

GC = dict(
  title="Cât costă să faci un joc cu AI?", desc="Calculează costul, timpul și prompturile jocului tău AI, pe gen și platformă.",
  badge="Nou · gratuit · fără cont", h1="Calculator de cost pentru jocuri cu AI",
  sub="Calculează costul și timpul ca să faci singur un joc 2D sau 3D cu AI. Calculatorul a fost verificat pe un joc real, lansat, și îți dă și lista de asseturi și un pachet de prompturi cu care să începi.",
  qProject="Jocul tău", name="Numele jocului", namePh="ex. Cat Café Merge", idea="Ideea într-o propoziție", ideaPh="ex. combini mobilier pentru pisici și decorezi o cafenea",
  qGenre="Gen", qScale="Dimensiune", sS="Mic", sSsub="≈ 2 săptămâni singur", sM="Mediu", sMsub="≈ 4 săptămâni", sL="Mare", sLsub="≈ 6 săptămâni", sXL="Foarte mare", sXLsub="≈ 3 luni sau mai mult",
  qStyle="Stil grafic", stPixel="Pixel art", stIllust="Ilustrație", stSimple="Simplu / vectorial",
  qDim="Afișare", d2="2D", d3="2.5D / modele 3D",
  qChars="Personaje / inamici", qAnim="Animație", aNone="Fără", aSimple="Simplă (3 mișcări)", aFull="Completă (6 mișcări)",
  qMusic="Piese muzicale", qSfx="Efecte sonore", sfFew="Puține", sfNormal="Normal", sfMany="Multe", qVoice="Replici vocale",
  qFeats="Funcții", qLangs="Limbi", qEngine="Engine", qTrailer="Trailer promo", yes="Da", no="Nu",
  qTools="Uneltele tale", qImg="Imagini", qCode="Programare", qMusicTool="Muzică", qSfxTool="Efecte sonore", q3dTool="Modele 3D (pentru 2.5D / 3D)", freeLib="Biblioteci gratuite", freeMusic="Pixabay (gratuit)", qModel="Model API",
  resTitle="De ce are nevoie jocul tău", cmpTitle="Cost și timp cu AI",
  promptTitle="Pachetul tău de prompturi", promptSub="Creat pe baza răspunsurilor tale. Prompturile pentru asseturi sunt în engleză, pentru că uneltele de imagine, muzică și sunet merg cel mai bine în engleză.",
  tDev="Start dezvoltare", tArt="Grafică", tMusic="Muzică", tSfx="Efecte sonore", tTrailer="Trailer", copy="Copiază", download="Descarcă tot (.md)",
  howTitle="Cum facem estimarea",
  how=["Dimensiunile se bazează pe jocuri reale făcute de o singură persoană cu agenți AI de programare: un joc mobil mic a durat cam 2 săptămâni, unul mediu cam 4, iar unul mare cam 6; unul foarte mare cam 3 luni. Genul, funcțiile, limbile și 3D-ul schimbă aceste cifre.",
       "Imagini = personaje × cadre de animație + fundaluri + obiecte + UI. Presupunem că păstrezi cam 1 din 3 generări, deci sunt de trei ori mai multe generări decât imagini.",
       "Tokenii de programare presupun că un agent precum Claude Code lucrează în cam 70% din zile și citește în jur de 20 de milioane de tokeni pe zi, mai ales context din cache. Costul API folosește prețul de listă actual al modelului ales; abonamentele se calculează pe lună."],
  srcTitle="Prețurile uneltelor folosite", srcNote=f"Verificat la {CHECKED}. Prețurile se schimbă des – verifică pagina de prețuri a fiecărei unelte înainte să cumperi.",
  faqTitle="Întrebări frecvente",
  faq=[("Cât costă să faci un joc 2D cu AI?", "Pentru un joc mobil mic, o persoană cu unelte AI cheltuie de obicei cam $100–300 pe abonamente și API și lucrează 2–3 săptămâni. Calculează-ți genul și dimensiunea cu calculatorul de mai sus."),
       ("De ce unelte AI am nevoie ca să fac un joc?", "De obicei patru: o unealtă de imagine pentru sprite-uri și fundaluri (Midjourney, Leonardo, Gemini, PixelLab, Scenario sau un API de imagine), o unealtă de muzică (Suno, Stable Audio, AIVA sau muzică gratuită de pe Pixabay), o unealtă pentru efecte sonore (ElevenLabs, Stable Audio sau biblioteci gratuite) și un agent de programare (Claude Code, Cursor sau Gemini CLI). Meshy te ajută cu modelele 3D, iar Higgsfield cu un video promo."),
       ("Câți tokeni costă să programezi un joc cu Claude Code?", "Agenții îți recitesc proiectul mereu, așa că un build de 2 săptămâni poate ajunge la câteva sute de milioane de tokeni, mai ales din cache. Cu Claude Max plătești o sumă fixă pe lună; pentru API, calculatorul arată costul modelului ales."),
       ("Pot folosi liber prompturile?", "Da. Copiază-le sau descarcă tot pachetul ca fișier Markdown și lipește-le în uneltele tale. Nimic din ce completezi nu este încărcat nicăieri.")],
  defName="Jocul meu", defIdea="un joc {genre} pentru {plat}",
  g_merge="Merge", g_puzzle="Puzzle", g_racing="Curse", g_idle="Idle", g_platformer="Platformer", g_rpg="RPG", g_novel="Visual novel", g_shooter="Shooter", g_match3="Match-3", g_tower="Tower defense", g_card="Cărți / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / management", g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Ritm", g_word="Cuvinte / quiz", g_farming="Fermă / simulare de viață", g_escape="Escape room / obiecte ascunse", g_board="Joc de masă", g_autobattler="Auto battler", g_survival="Supraviețuire / crafting", g_fishing="Pescuit", g_sports="Sport", g_fighting="Lupte", g_pet="Îngrijire animăluțe", g_minigames="Colecție de minijocuri", g_metroidvania="Metroidvania", g_strategy="Strategie / 4X", g_gacha="RPG gacha de colecție", g_horror="Horror", g_sandbox="Sandbox", g_mmo="MMO / RPG online", gOther="Mai multe ▾",
  f_ads="Reclame", f_iap="Achiziții în aplicație", f_save="Salvare / încărcare", f_rank="Clasament", f_online="Multiplayer online",
  devIntro="Ești un dezvoltator de jocuri cu experiență. Ajută-mă să construiesc „{name}”, un joc {dim} de tip {genre} pentru {plat} cu {engine}.",
  qPlat="Se lansează pe", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web", pls_android="Google Play, o singură dată", pls_mobile="Google Play $25 + Apple $99/an", pls_pc="Steam Direct, per joc", pls_web="", l_store="Taxe magazin", l_server="Server",
  devIdea="Idee:", devScope="Amploare: {chars} personaje, {bg} fundaluri, {items} obiecte, {music} piese muzicale, {sfx} efecte sonore, {langs} limbă/limbi.",
  devFeats="Funcții:", devRules="Reguli: păstrează codul simplu și modular; o singură funcție pe pas; după fiecare pas spune-mi cum îl testez pe telefon; folosește forme placeholder până îți dau grafica reală.",
  devSteps="Construiește-l în acești pași:", st1="Setup proiect, structură de foldere, flux de scene (titlu → joc → rezultat)", st2="Bucla de gameplay de bază cu grafică placeholder",
  st3="Scor, progres și curba de dificultate", st4="UI: meniuri, HUD, pauză, setări", st5="Adaugă: {feats}", st6="Integrează grafica reală, muzica și efectele sonore", st7="Finisare, verificare de performanță și build Android",
  devStart="Începe cu pasul 1. Întreabă-mă tot ce ai nevoie înainte să scrii cod.",
  rImages="Imagini", rImagesSub="{chars} personaje · {frames} cadre · {bg} fundaluri · {items} obiecte · {ui} UI", rAudio="Muzică + sunet", rAudioSub="piese + efecte",
  rCode="Linii de cod", rCodeSub="estimat", rTokens="Tokeni de programare", rTokensSub="≈ {api} prin API",
  l_art="Grafică", l_music="Muzică", l_sfx="Sunet / voce", l_code="Cod", l_d3="Modele 3D", l_trailer="Trailer",
  p_value="💰 Cel mai ieftin", p_normal="⚖️ Standard", p_max="🚀 Top", pCustom="Combinația ta", tier_value="buget", tier_normal="standard", tier_max="premium", pHint="Apasă pe o combinație ca să schimbi toate uneltele deodată sau schimbă-le pe rând mai jos.",
  days="{n} zile", monthsN="{n} luni", capWarn="Limita de utilizare a acestui abonament probabil nu ajunge pentru programare zilnică cu un agent – socotește timp de așteptare sau costuri în plus.",
  qa='Pe scurt: să faci singur un joc mobil 2D mic cu unelte AI durează cam 2–3 săptămâni și costă în jur de $50–180 pe abonamente și API (octombrie 2026). Cea mai mare parte e abonamentul de programare cu AI.', sumTitle='Cost și timp pe gen și dimensiune', sumNote='Fiecare celulă: timp de dezvoltare · cost de la cea mai ieftină la combinația standard. O persoană cu AI, USD fără TVA, cu taxele de magazin incluse. Verificat la {date}.',
  cTax="TVA inclus ({pct}%)", cFx="Curs de schimb din {date}, aproximativ",
  hireRef="Pentru comparație: să angajezi freelanceri pentru un joc de dimensiunea asta pornește de obicei de la <b>{min}+</b>, iar ofertele pot varia de zece ori sau mai mult în funcție de țară și calitate.",
  noTrailer="Activează „Trailer promo” ca să primești prompturi pentru trailer.",
  copied="Copiat ✓", packTitle="pachet de prompturi",
  related="Vezi și", rel=[("/ro/agents", "Calculator de cost pentru coding agents"), ("/ro/image", "Cost per imagine AI"), ("/ro/plans", "Abonament sau API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (raiduri pe baze)", g_plus1="+1 pe secundă (evadare / viteză)", g_verbsim="Sim cu acțiune simplă (tip curățat cartofi)",
  g_coophorror="Horror co-op", g_duels="Dueluri 1v1", g_rng="RNG / colecționat cu noroc", g_coopobby="Obby co-op pentru 2",
  rbxTitle="🔥 În trend pe Roblox acum", rbxSub="Tipuri de jocuri care urcă în topurile Roblox, cu jucători simultani. Verificat la {date} pe Roblox Charts.", rbxUse="Folosește asta →",
  rbxMoney="Pe Roblox nu există taxă de magazin, iar Roblox rulează serverele gratuit. Câștigi Robux din game passes și developer products (păstrezi 70%) și din Premium Payouts, apoi îi schimbi prin DevEx la $0,0038 per Robux (minimum 30.000 Robux). Exemplu: vânzări de 10.000 Robux → 7.000 Robux → cam $27.",
  devIntroRbx="Ești un dezvoltator Roblox cu experiență. Ajută-mă să construiesc „{name}”, un experience de tip {genre} pe Roblox, în Roblox Studio cu Luau.",
  rbxDev="Specific Roblox: pune logica jocului în ServerScriptService, iar UI-ul și inputul clientului în StarterPlayerScripts / StarterGui; comunicarea între ele doar prin RemoteEvents și nu te încrede niciodată în client. Salvează progresul cu DataStoreService (cu reîncercări). Vinde game passes și developer products prin MarketplaceService. Folosește Roblox Assistant în Studio pentru modificări mici și modele 3D și fă fiecare pas testabil în modul Play.",
  rbxPublish="Finisare, test în Studio cu 2+ jucători, setare iconiță și thumbnails și publicare pe Roblox",
)

NAV = "Cost joc"
