# -*- coding: utf-8 -*-
"""Slovak (sk) strings for the AI game cost calculator + Roblox block. Same keys as gamecost_i18n.NL / roblox_i18n.RBX["nl"]."""
CHECKED = "2026-10-05"  # same value as gamecost_i18n.CHECKED (defined there, not imported to avoid cycles)

GC = dict(
  title="Koľko stojí vytvoriť hru s AI?", desc="Vypočítaj náklady, čas a prompty pre AI hru podľa žánru, veľkosti a platformy.",
  badge="Nové · zadarmo · bez registrácie", h1="Kalkulačka nákladov na hru s AI",
  sub="Odpovedz na pár otázok o svojej 2D hre. Dostaneš zoznam assetov, náklady a čas na vytvorenie s AI nástrojmi, počet tokenov a balík promptov, s ktorým môžeš začať ešte dnes.",
  qProject="Tvoja hra", name="Názov hry", namePh="napr. Mačacia kaviareň Merge", idea="Nápad v jednej vete", ideaPh="napr. spájaj mačací nábytok a zariaď kaviareň",
  qGenre="Žáner", qScale="Veľkosť", sS="Malá", sSsub="≈ 2 týždne sám", sM="Stredná", sMsub="≈ 4 týždne", sL="Veľká", sLsub="≈ 6 týždňov", sXL="Veľmi veľká", sXLsub="≈ 3 mesiace a viac",
  qStyle="Grafický štýl", stPixel="Pixel art", stIllust="Ilustrácia", stSimple="Jednoduchý / vektor",
  qDim="Zobrazenie", d2="2D", d3="2.5D / 3D modely",
  qChars="Postavy / nepriatelia", qAnim="Animácia", aNone="Žiadna", aSimple="Jednoduchá (3 pohyby)", aFull="Plná (6 pohybov)",
  qMusic="Hudobné skladby", qSfx="Zvukové efekty", sfFew="Málo", sfNormal="Bežne", sfMany="Veľa", qVoice="Nahovorené repliky",
  qFeats="Funkcie", qLangs="Jazyky", qEngine="Engine", qTrailer="Propagačný trailer", yes="Áno", no="Nie",
  qTools="Tvoje nástroje", qImg="Obrázky", qCode="Programovanie", qMusicTool="Hudba", qSfxTool="Zvukové efekty", q3dTool="3D modely (pri 2.5D / 3D)", freeLib="Bezplatné knižnice", freeMusic="Pixabay (zadarmo)", qModel="Model API",
  resTitle="Čo tvoja hra potrebuje", cmpTitle="Náklady a čas s AI",
  promptTitle="Tvoj balík promptov", promptSub="Vytvorené z tvojich odpovedí. Prompty pre assety sú v angličtine, pretože nástroje na obrázky, hudbu a zvuky fungujú najlepšie po anglicky.",
  tDev="Štart vývoja", tArt="Grafika", tMusic="Hudba", tSfx="Zvukové efekty", tTrailer="Trailer", copy="Kopírovať", download="Stiahnuť všetko (.md)",
  howTitle="Ako to odhadujeme",
  how=["Veľkosti vychádzajú zo skutočných hier, ktoré vytvoril jeden človek s AI kódovacími agentmi: malá mobilná hra trvala asi 2 týždne, stredná asi 4 a veľká asi 6; veľmi veľká asi 3 mesiace. Žáner, funkcie, jazyky a 3D tieto čísla menia.",
       "Obrázky = postavy × snímky animácie + pozadia + predmety + UI. Počítame s tým, že si necháš zhruba 1 z 3 generovaní, takže generovaní je trikrát viac ako obrázkov.",
       "Kódovacie tokeny predpokladajú agenta ako Claude Code, ktorý pracuje asi 70 % dní a denne prečíta okolo 20 miliónov tokenov, väčšinou z cache. Náklady API používajú aktuálnu cenníkovú cenu zvoleného modelu; predplatné sa počíta po mesiacoch."],
  srcTitle="Použité ceny nástrojov", srcNote=f"Overené {CHECKED}. Ceny sa často menia – pred nákupom si skontroluj cenník každého nástroja.",
  faqTitle="Časté otázky",
  faq=[("Koľko stojí vytvoriť 2D hru s AI?", "Pri malej mobilnej hre minie jeden človek s AI nástrojmi zvyčajne asi 100–300 $ za predplatné a API a zaberie mu to 2–3 týždne. Svoj žáner a veľkosť si vypočítaj v kalkulačke vyššie."),
       ("Aké AI nástroje potrebujem na vytvorenie hry?", "Zvyčajne štyri: nástroj na obrázky pre sprity a pozadia (Midjourney, Leonardo, Gemini, PixelLab, Scenario alebo obrázkové API), nástroj na hudbu (Suno, Stable Audio, AIVA alebo bezplatná hudba z Pixabay), nástroj na zvukové efekty (ElevenLabs, Stable Audio alebo bezplatné knižnice) a kódovacieho agenta (Claude Code, Cursor alebo Gemini CLI). Meshy pomôže s 3D modelmi, Higgsfield s propagačným videom."),
       ("Koľko tokenov stojí naprogramovať hru s Claude Code?", "Agenti tvoj projekt stále znova čítajú, takže dvojtýždňový vývoj môže dosiahnuť niekoľko sto miliónov tokenov, väčšinou z cache. S Claude Max platíš pevnú sumu mesačne; pri API ukáže kalkulačka cenu zvoleného modelu."),
       ("Môžem prompty voľne používať?", "Áno. Skopíruj ich alebo si stiahni celý balík ako súbor Markdown a vlož ich do svojich nástrojov. Nič z toho, čo zadáš, sa nikam nenahráva.")],
  defName="Moja hra", defIdea="hra žánru {genre} pre {plat}",
  g_merge="Merge", g_puzzle="Logická", g_racing="Pretekárska", g_idle="Idle", g_platformer="Plošinovka", g_rpg="RPG", g_novel="Vizuálny román", g_shooter="Strieľačka", g_match3="Match-3", g_tower="Tower defense", g_card="Kartová / deckbuilder", g_survivor="Survivor-like", g_tycoon="Tycoon / budovateľská", g_hyper="Hypercasual", g_runner="Runner", g_rhythm="Rytmická", g_word="Slovná / kvíz", g_farming="Farma / simulácia života", g_escape="Úniková hra / hľadanie predmetov", g_board="Stolová hra", g_autobattler="Auto battler", g_survival="Survival / crafting", g_fishing="Rybárčenie", g_sports="Športová", g_fighting="Bojovka", g_pet="Starostlivosť o zvieratká", g_minigames="Zbierka minihier", g_metroidvania="Metroidvania", g_strategy="Stratégia / 4X", g_gacha="Gacha zberateľské RPG", g_horror="Horor", g_sandbox="Sandbox", g_mmo="MMO / online RPG", gOther="Ďalšie ▾",
  f_ads="Reklamy", f_iap="Nákupy v aplikácii", f_save="Ukladanie / načítanie", f_rank="Rebríček", f_online="Online multiplayer",
  devIntro="Si skúsený vývojár hier. Pomôž mi vytvoriť \"{name}\", 2D hru žánru {genre} pre {plat} v engine {engine}.",
  qPlat="Vychádza na", pl_android="Android", pl_mobile="Android + iOS", pl_pc="PC (Steam)", pl_web="Web", pls_android="Google Play, jednorazovo", pls_mobile="Google Play $25 + Apple $99/rok", pls_pc="Steam Direct, za hru", pls_web="", l_store="Poplatky obchodu", l_server="Server",
  devIdea="Nápad:", devScope="Rozsah: {chars} postáv, {bg} pozadí, {items} predmetov, {music} hudobných skladieb, {sfx} zvukových efektov, {langs} jazyk(ov).",
  devFeats="Funkcie:", devRules="Pravidlá: drž kód jednoduchý a modulárny; jedna funkcia na krok; po každom kroku mi povedz, ako ho otestovať na telefóne; používaj zástupné tvary, kým ti nedám skutočnú grafiku.",
  devSteps="Postav to v týchto krokoch:", st1="Nastavenie projektu, štruktúra priečinkov, tok scén (titulka → hra → výsledok)", st2="Hlavná herná slučka so zástupnou grafikou",
  st3="Skóre, postup a krivka obtiažnosti", st4="UI: menu, HUD, pauza, nastavenia", st5="Pridať: {feats}", st6="Vložiť finálnu grafiku, hudbu a zvukové efekty", st7="Doladenie, kontrola výkonu a build pre Android",
  devStart="Začni krokom 1. Skôr než začneš písať kód, opýtaj sa ma na všetko, čo potrebuješ.",
  rImages="Obrázky", rImagesSub="{chars} postáv · {frames} snímok · {bg} pozadí · {items} predmetov · {ui} UI", rAudio="Hudba + zvuky", rAudioSub="skladby + efekty",
  rCode="Riadky kódu", rCodeSub="odhad", rTokens="Kódovacie tokeny", rTokensSub="≈ {api} cez API",
  l_art="Grafika", l_music="Hudba", l_sfx="Zvuk / hlas", l_code="Kód", l_d3="3D modely", l_trailer="Trailer",
  p_value="💰 Najvýhodnejšie", p_normal="⚖️ Štandard", p_max="🚀 Špička", pCustom="Tvoja kombinácia", tier_value="lacné", tier_normal="štandard", tier_max="prémiové", pHint="Klikni na kombináciu a prepneš všetky nástroje naraz, alebo ich nižšie meň jeden po druhom.",
  days="{n} dní", monthsN="{n} mes.", capWarn="Limit využitia tohto predplatného pravdepodobne nestačí na každodenné kódovanie s agentom – počítaj s čakaním alebo príplatkami.",
  qa="Stručne: vytvoriť sám malú mobilnú 2D hru s AI nástrojmi trvá asi 2–3 týždne a stojí okolo 50–180 $ za predplatné a API (október 2026). Najväčšiu časť tvorí predplatné AI na kódovanie.", sumTitle="Náklady a čas podľa žánru a veľkosti", sumNote="Každá bunka: čas vývoja · náklady od najvýhodnejšej po štandardnú kombináciu. Jeden človek s AI, USD bez DPH, vrátane poplatkov obchodu. Overené {date}.",
  cTax="Vrátane DPH ({pct} %)", cFx="Kurz zo dňa {date}, zaokrúhlené",
  hireRef="Pre porovnanie: najať freelancerov na hru tejto veľkosti zvyčajne začína na <b>{min}+</b> a ponuky sa môžu podľa krajiny a kvality líšiť aj desaťnásobne a viac.",
  noTrailer="Zapni „Propagačný trailer“ a dostaneš prompty pre trailer.",
  copied="Skopírované ✓", packTitle="balík promptov",
  related="Pozri aj", rel=[("/sk/agents", "Náklady na kódovacích agentov"), ("/sk/image", "Cena za AI obrázok"), ("/sk/plans", "Predplatné, alebo API?")],
)

RBX = dict(
  pl_roblox="Roblox", pls_roblox="",
  g_steal="Steal a ___ (vykrádanie základní)", g_plus1="+1 za sekundu (útek / rýchlosť)", g_verbsim="Simulátor jednoduchej činnosti (typ lúpanie zemiakov)",
  g_coophorror="Kooperatívny horor", g_duels="Súboje 1 na 1", g_rng="RNG / zbieranie so šťastím", g_coopobby="Kooperatívne obby pre 2",
  rbxTitle="🔥 Teraz letí na Robloxe", rbxSub="Typy hier, ktoré stúpajú v rebríčkoch Robloxu, s počtom súčasných hráčov. Overené {date} na Roblox Charts.", rbxUse="Použiť →",
  rbxMoney="Na Robloxe nie sú žiadne poplatky obchodu a servery Roblox prevádzkuje zadarmo. Robuxy zarábaš na game passoch a developer products (necháš si 70 %) a z Premium Payouts, a potom ich cez DevEx premeníš na peniaze za $0,0038 za Robux (minimum 30 000 Robuxov). Príklad: tržby 10 000 Robuxov → 7 000 Robuxov → asi $27.",
  devIntroRbx="Si skúsený vývojár pre Roblox. Pomôž mi vytvoriť \"{name}\", zážitok žánru {genre} na Robloxe, v Roblox Studiu s Luau.",
  rbxDev="Špecifiká Robloxu: hernú logiku daj do ServerScriptService a UI a vstup klienta do StarterPlayerScripts / StarterGui; nech spolu komunikujú len cez RemoteEvents a nikdy klientovi never. Postup ukladaj cez DataStoreService (s opakovanými pokusmi). Game passy a developer products predávaj cez MarketplaceService. Na drobné úpravy a 3D modely používaj Roblox Assistant v Studiu a každý krok sprav testovateľný v režime Play.",
  rbxPublish="Doladiť, otestovať v Studiu s 2+ hráčmi, nastaviť ikonu a náhľady a publikovať na Roblox",
)

NAV = "Cena hry"
